export default function ClausePage() {
    return (
        <div className="w-full text-red-500">
            <div className="mx-auto w-full pt-16 px-8 md:px-32">
                <h1 className="text-4xl font-bold mb-4">ĐIỀU KHOẢN</h1>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">1. GIỚI THIỆU</h2>
                    <p className="mb-4">
                        1.1. Chào mừng bạn đến với Vivabyte. Điều Khoản dịch vụ này quy định các điều khoản và điều kiện theo đó Công ty Cổ phần Giải trí và Thể thao Điện tử Việt Nam và các công ty liên kết (gọi riêng và gọi chung là &ldquo;Vivabyte”, &ldquo;chúng tôi” hoặc &ldquo;của chúng tôi”) cung cấp cho:</p>
                    <p className="mb-4">(a) Các trò chơi trên máy tính và điện thoại di động (“Trò chơi”);</p>
                    <p className="mb-4">(b) Bất cứ ứng dụng, website, trò chơi hoặc dịch vụ nào khác liên quan đến Điều Khoản dịch vụ này, bất kể cách thức bạn truy cập hoặc sử dụng chúng, bao gồm cả việc thông qua các thiết bị di động(gọi chung là “Các Dịch Vụ”)</p>
                    <p className="mb-4">1.2. Các Dịch Vụ cũng bao gồm bất cứ Dịch vụ nào được cung cấp bởi phần mềm Vivabyte Platform trên máy khách hàng, bất cứ dịch vụ nào được cung cấp thông qua các Trò chơi hoặc Trang Web của chúng tôi, và tất cả các thông tin, các trang được liên kết web được liên kết, các tính năng, dữ liệu, văn bản, hình ảnh, hình chụp, đồ họa, nhạc, âm thanh, video, thông báo, tag, nội dung, lập trình, phần mềm, các dịch vụ ứng dụng (bao gồm nhưng không giới hạn ở bất kỳ dịch vụ ứng dụng di động nào) hoặc các tài liệu khác được cung cấp thông qua chúng tôi (&ldquo;Nội Dung”). Bất kỳ bản cập nhật, nâng cấp và bất kỳ tính năng mới nào được thêm vào hoặc để tăng cường Các Dịch Vụ đều phải tuân thủ các Điều Khoản Dịch Vụ này. Không phải tất cả các Dịch vụ hay Nội Dung đều có ở tất cả các thị trường.</p>
                    <p className="mb-4">1.3. Vui lòng đọc kỹ Điều Khoản Dịch vụ này trước khi sử dụng Dịch vụ hoặc mở tài khoản Vivabyte (&ldquo;Tài Khoản&rdquo;) để bạn với tư cách là Người dùng nhận thức được các quyền và nghĩa vụ hợp pháp của mình đối với Vivabyte và các Dịch vụ. Người dùng đề cập đến một cá nhân đăng ký Tài Khoản với chúng tôi hoặc người khác truy cập hoặc sử dụng Dịch vụ (được gọi riêng và gọi chung là “Người dùng”, “bạn” hoặc “của bạn”).</p>
                    <p className="mb-4">1.4. BẰNG VIỆC SỬ DỤNG CÁC DỊCH VỤ HOẶC MỞ MỘT TÀI KHOẢN, BẠN CHO BIẾT RẰNG BẠN CHẤP NHẬN KHÔNG THỂ HỦY NGANG ĐỐI VỚI CÁC ĐIỀU KHOẢN DỊCH VỤ NÀY. NẾU BẠN KHÔNG ĐỒNG Ý VỚI CÁC ĐIỀU KHOẢN DỊCH VỤ NÀY, VUI LÒNG KHÔNG SỬ DỤNG CÁC DỊCH VỤ CỦA CHÚNG TÔI.</p>
                    <p className="mb-4">
                        1.4. NẾU BẠN DƯỚI 18 TUỔI HOẶC TRONG &ldquo;ĐỘ TUỔI TRƯỞNG THÀNH&rdquo; Ở NƠI BẠN SỐNG, BẠN PHẢI XIN PHÉP CHA MẸ HOẶC NGƯỜI GIÁM HỘ HỢP PHÁP ĐỂ MỞ MỘT TÀI KHOẢN VÀ CHA MẸ HOẶC NGƯỜI GIÁM HỘ HỢP PHÁP PHẢI ĐỒNG Ý VỚI CÁC ĐIỀU KHOẢN DỊCH VỤ NÀY. NẾU BẠN KHÔNG BIẾT BẠN CÓ THUỘC &ldquo;ĐỘ TUỔI TRƯỞNG THÀNH&rdquo; Ở NƠI BẠN SỐNG HAY KHÔNG, HOẶC KHÔNG HIỂU PHẦN NÀY, VUI LÒNG KHÔNG TẠO TÀI KHOẢN CHO ĐẾN KHI BẠN ĐÃ NHỜ CHA MẸ HOẶC NGƯỜI GIÁM HỘ HỢP PHÁP CỦA BẠN GIÚP ĐỠ. NẾU BẠN LÀ CHA MẸ HOẶC NGƯỜI GIÁM HỘ HỢP PHÁP CỦA MỘT TRẺ VỊ THÀNH NIÊN MUỐN TẠO MỘT TÀI KHOẢN, BẠN PHẢI CHẤP NHẬN CÁC ĐIỀU KHOẢN DỊCH VỤ NÀY THAY MẶT CHO TRẺ VỊ THÀNH NIÊN ĐÓ VÀ BẠN SẼ CHỊU TRÁCH NHIỆM ĐỐI VỚI TẤT CẢ HOẠT ĐỘNG SỬ DỤNG TÀI KHOẢN HAY CÁC DỊCH VỤ, BAO GỒM CÁC GIAO DỊCH MUA HÀNG HOẶC CÁC GIAO DỊCH KHÁC DO TRẺ VỊ THÀNH NIÊN THỰC HIỆN LIÊN QUAN ĐẾN CÁC DỊCH VỤ, CHO DÙ TÀI KHOẢN CỦA TRẺ VỊ THÀNH NIÊN ĐÓ ĐƯỢC MỞ VÀO LÚC NÀY HAY ĐƯỢC TẠO SAU NÀY VÀ CHO DÙ TRẺ VỊ THÀNH NIÊN CÓ ĐƯỢC BẠN GIÁM SÁT TRONG GIAO DỊCH MUA HÀNG ĐÓ HOẶC CÁC HÀNH VI KHÁC SỬ DỤNG CÁC DỊCH VỤ HAY KHÔNG.</p>
                    <p className="mb-4">1.5. Vivabyte bảo lưu quyền chỉnh sửa các Điều Khoản Dịch Vụ này vào bất kỳ lúc nào hoặc trên cơ sở thông báo cho Người dùng, phù hợp với pháp luật hiện hành. Chúng tôi sẽ cập nhật định kỳ cho bạn bất kỳ sửa đổi nào đối với các Điều Khoản Dịch vụ này, bao gồm cả việc đăng các Điều Khoản Dịch vụ đã sửa đổi đó tại đây. Chúng tôi khuyến khích bạn kiểm tra trang này thường xuyên để ghi nhận bất kỳ thay đổi nào. Trong phạm vi tối đa được pháp luật cho phép, việc bạn tiếp tục truy cập hoặc sử dụng Dịch vụ sẽ được coi là sự chấp nhận không thể hủy ngang đối với những sửa đổi đó.</p>
                    <p className="mb-4">
                        1.6. Vivabyte có quyền thay đổi, điều chỉnh, đình chỉ hoặc ngừng bất kỳ phần nào của Các Dịch Vụ vào bất kỳ lúc nào. Vivabyte có thể ra mắt Các Dịch Vụ nhất định hoặc các tính năng của chúng trong một phiên bản beta, phiên bản này có thể không hoạt động chính xác hoặc theo cùng cách như phiên bản cuối cùng, và chúng tôi sẽ không chịu trách nhiệm pháp lý trong các trường hợp đó. Vivabyte cũng có thể toàn quyền áp dụng giới hạn đối với các tính năng nhất định hoặc hạn chế quyền truy cập của bạn đối với một phần hoặc toàn bộ Các Dịch Vụ mà không cần thông báo hoặc phải chịu trách nhiệm pháp lý.</p>
                    <p className="mb-4">
                        1.7. Vivabyte có quyền từ chối cho phép bạn truy cập Các Dịch Vụ hoặc cho phép bạn mở Tài Khoản vì bất kỳ lý do gì.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">2. BẢO MẬT</h2>
                    <p className="mb-4">2.1. Vivabyte rất coi trọng việc bảo mật thông tin của bạn. Để bảo vệ các quyền của bạn một cách hiệu quả hơn, chúng tôi đã cung cấp Chính Sách Bảo Mật của Vivabyte để giải thích chi tiết về các cách thức bảo mật thông tin của chúng tôi. Vui lòng xem Chính Sách Bảo Mật để hiểu được cách thức Vivabyte thu thập và sử dụng thông tin liên kết với Tài Khoản của bạn và/hoặc việc bạn sử dụng Các Dịch Vụ. Bằng việc truy cập hoặc sử dụng Các Dịch Vụ hoặc đồng ý với các Điều Khoản Dịch Vụ này, bạn đồng ý cho phép Vivabyte thu thập, sử dụng, tiết lộ, xử lý và/hoặc chuyển Nội Dung và dữ liệu cá nhân của bạn như mô tả trong Chính Sách Bảo Mật này.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">3.
                        GIỚI HẠN VỀ QUYỀN SỬ DỤNG</h2>
                    <p className="mb-4">3.1. Vivabyte cấp cho bạn quyền sử dụng không độc quyền, không thể chuyển giao có giới hạn để cài đặt Phần mềm và để truy cập và/hoặc sử dụng Các Dịch Vụ, tuân theo các điều khoản và điều kiện của Điều Khoản Dịch Vụ này và với mục đích sử dụng cá nhân. Việc cấp quyền này không cho phép bạn sử dụng vì bất kỳ mục đích thương mại nào hay sử dụng vì mục đích phái sinh đối với Các Dịch Vụ này (bao gồm nhưng không giới hạn ở bất kỳ yếu tố riêng lẻ nào, bao gồm nhưng không giới hạn Trò chơi, Phần mềm hoặc Nội Dung). Tất cả các quyền không được cấp quyền một cách rõ ràng bởi Vivabyte theo Điều Khoản dịch vụ này đều được bảo lưu bởi Vivabyte. Bất cứ mã, nội dung của bên thứ ba nào được liên kết hoặc tham chiếu từ Các Dịch Vụ, đều được cấp quyền sử dụng bởi bên thứ ba sở hữu các nội dung, mã này mà không phải là Vivabyte.</p>
                    <p className="mb-4">
                        3.2. Bạn xác nhận và đồng ý rằng tất cả các quyền, quyền sở hữu và các quyền Sở hữu trí tuệ liên quan đến các Dịch vụ (bao gồm nhưng không giới hạn bất cứ tác phẩm phái sinh, tiêu đề mã máy tính, các đối tượng, các giao diện, các nhân vật, tên các nhân vật, câu chuyện, các hội thoại, các khẩu hiệu, các địa điểm, các khái niệm, các tác phẩm nghệ thuật, đồ họa, hoạt hình, âm thanh, bản hợp âm, các hiệu ứng âm thanh hình ảnh, đoạn văn, màn hình hiển thị, phương pháp hoạt động, quyền nhân thân, các applet được cấu thành trong các Dịch vụ, và bất cứ tài liệu nào có liên quan) đều là tài sản của Vivabyte, và tùy từng trường hợp thuộc sở hữu của bên thứ ba như được xác định trong Các Dịch Vụ.</p>
                    <p className="mb-4">3.3. Bằng việc sử dụng hoặc truy cập Các Dịch Vụ, bạn đồng ý tuân thủ các quy định pháp luật về sở hữu trí tuệ hiện hành đối với vấn đề bảo hộ bản quyền, thương hiệu, nhãn hiệu dịch vụ, Các Dịch Vụ và Nội Dung của nó. Bạn đồng ý không sao chép, phát tán, tái xuất bản, gửi, trưng bày công khai, trình diễn công khai, điều chỉnh, sửa đổi, cho thuê, bán, hay tạo phó bản của bất kỳ phần nào của Các Dịch Vụ hoặc Nội Dung của nó. Nếu không có sự đồng ý trước bằng văn bản của chúng tôi, Bạn cũng không được nhân bản hoặc chỉnh sửa một phần hay toàn bộ Các Dịch Vụ trên máy chủ khác hoặc như một phần của bất kỳ trang web nào khác. Ngoài ra, bạn đồng ý rằng bạn sẽ không sử dụng bất kỳ công cụ robot, spider hay bất kỳ thiết bị tự động hay quy trình thủ công nào khác để theo dõi hay sao chép Nội Dung của chúng tôi, nếu không có sự đồng ý trước bằng văn bản của chúng tôi (thỏa thuận này áp dụng cho các công cụ tìm kiếm cơ bản trên các website kết nối người dùng trực tiếp đến website đó).</p>
                    <p className="mb-4">3.4. Chúng tôi hoan nghênh bạn liên kết đến Trang Web này từ trang web của bạn, miễn là trang web của bạn không ngụ ý rằng Vivabyte ủng hộ hay liên kết với trang web của bạn. Bạn thừa nhận rằng Vivabyte, vào bất kỳ lúc nào, có thể tự quyền quyết định về việc ngừng cung cấp bất kỳ phần nào của Các Dịch Vụ mà không cần thông báo.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">4. ĐIỀU KHOẢN SỬ DỤNG</h2>
                    <p className="mb-4">4.1. Quyền sử dụng Các Dịch Vụ có hiệu lực đến khi bị chấm dứt. Quyền sử dụng này sẽ chấm dứt như quy định trong các Điều Khoản Dịch Vụ này hoặc nếu bạn không tuân thủ bất kỳ điều khoản hay điều kiện nào của các Điều Khoản Dịch Vụ này. Trong trường hợp đó, Vivabyte sẽ không cần thông báo để áp dụng sự chấm dứt đó.</p>
                    <p className="mb-4">4.2. Bạn đồng ý không:</p>
                    <p className="mb-4">
                        4.2.1. tải lên, đăng tin, gửi email, gửi hoặc cung cấp theo cách khác bất kỳ Nội Dung nào được cho là bất hợp pháp, có hại, đe dọa, xúc phạm, quấy rối, làm lo lắng, tra tấn, nhục mạ, phản cảm, tục tĩu, phỉ báng, xâm phạm quyền riêng tư của người khác, thù địch, hoặc phân biệt chủng tộc, sắc tộc hoặc các hành động đáng lên án khác;</p>
                    <p className="mb-4">
                        4.2.2. sử dụng Các Dịch Vụ để gây hại cho trẻ vị thành niên hoặc tạo các Nội Dung có sẵn gây hại cho trẻ nhỏ hoặc trẻ vị thành niên dưới bất kỳ hình thức nào;</p>
                    <p className="mb-4">4.2.3. tải lên, đăng bài, email, truyền tải hoặc cung cấp bất kỳ Nội Dung nào vi phạm quyền, bao gồm mọi bằng sáng chế, nhãn hiệu, bản quyền, sở hữu trí tuệ hoặc các quyền sở hữu khác của bất kỳ bên nào</p>
                    <p className="mb-4">4.2.4. sử dụng Các Dịch Vụ để mạo danh bất kỳ cá nhân hay tổ chức nào; hoặc giả mạo khác việc bạn liên kết với một cá nhân hay tổ chức;</p>
                    <p className="mb-4">4.2.5. giả mạo các đầu đề hoặc các hành vi thao túng khác đối với các yếu tố danh định nhằm che giấu hoặc gây hiểu nhầm về nguồn gốc của bất kỳ Nội Dung hay thông điệp nào được truyền tải qua Các Dịch Vụ;</p>
                    <p className="mb-4">4.2.6. xóa gỡ bất kỳ thông báo độc quyền nào ra khỏi Các Dịch Vụ</p>
                    <p className="mb-4">4.2.7. thực hiện, cho phép hoặc ủy quyền sửa đổi, tạo ra các bản phái sinh, hoặc biên dịch Các Dịch Vụ mà không được sự cho phép của Vivabyte;</p>
                    <p className="mb-4">4.2.8. sử dụng Các Dịch Vụ vì bất kỳ mục đích thương mại nào hay vì lợi ích của bất kỳ bên thứ ba hoặc theo bất kỳ hình thức nào không được phép theo các quyền đã được cấp.</p>
                    <p className="mb-4">4.2.9. sử dụng Các Dịch vụ vì mục đích gian lận hoặc phi pháp, bao gồm cho bất kỳ mục đích nào liên quan hoặc khuyến khích rửa tiền hoặc cờ bạc hoặc không nhất quán hoặc trái với luật hiện hành</p>
                    <p className="mb-4">4.2.10. cố gắng dịch ngược, thiết kế đối chiếu, tháo rời hoặc hack Dịch vụ (hoặc bất kỳ phần nào trong đó) hoặc bất kỳ mạng nào được kết nối với Dịch vụ, hoặc cố gắng vi phạm, loại bỏ hoặc vượt qua bất kỳ biện pháp xác thực, công nghệ mã hóa hoặc biện pháp bảo mật nào do Vivabyte thực hiện liên quan đến Dịch vụ, bất kỳ mạng nào được kết nối hoặc liên kết với Dịch vụ và/hoặc bất kỳ dữ liệu nào do Vivabyte truyền, xử lý hoặc lưu trữ;</p>
                    <p className="mb-4">4.2.11. tải lên, đăng, gửi email, truyền hoặc cung cấp bất kỳ Nội Dung nào có chứa vi rút phần mềm hoặc bất kỳ mã máy tính, tệp hoặc chương trình nào khác được thiết kế để làm gián đoạn, phá hủy, thay đổi và/hoặc giới hạn chức năng của Dịch vụ và/hoặc bất kỳ tài nguyên máy tính nào thuộc về Vivabyte hoặc Người dùng của Vivabyte;</p>
                    <p className="mb-4">4.2.12. tải lên, đăng, gửi email, truyền hoặc cung cấp bất kỳ Nội Dung nào đe dọa sự thống nhất, toàn vẹn, quốc phòng, an ninh hoặc chủ quyền của quốc gia hoặc quyền tài phán mà bạn đang truy cập hoặc sử dụng dịch vụ, quan hệ hữu nghị với nước ngoài, hoặc trật tự công cộng, hoặc gây ra sự xúi giục thực hiện bất kỳ hành vi phạm tội có thể hiểu được hoặc ngăn cản việc điều tra bất kỳ hành vi phạm tội nào hoặc xúc phạm các quốc gia khác;</p>
                    <p className="mb-4">4.2.13. cố gắng gạ gẫm, thu thập hoặc thu thập bất kỳ thông tin nào về hoặc liên quan đến Người dùng hoặc Chủ tài khoản khác, bao gồm nhưng không giới hạn bất kỳ dữ liệu cá nhân, thông tin tài khoản, mật khẩu hoặc thông tin khác</p>
                    <p className="mb-4">4.2.14. cố gắng hoặc có được quyền truy cập trái phép vào bất kỳ phần hoặc tính năng nào của Dịch vụ bao gồm bất kỳ tài khoản nào khác của Người dùng</p>
                    <p className="mb-4">4.2.15. tải lên, đăng, gửi email, gửi hoặc cung cấp dưới hình thức khác bất kỳ Nội Dung nào mà bạn không có quyền cung cấp theo bất kỳ điều luật nào hay theo các quan hệ hợp đồng hoặc ủy thác (chẳng hạn như thông tin nội gián, thông tin độc quyền và thông tin mật đã biết hoặc được tiết lộ trong các mối quan hệ tuyển dụng hoặc theo các thỏa thuận không tiết lộ thông tin);</p>
                    <p className="mb-4">4.2.16. tải lên, đăng, gửi email, gửi hoặc cung cấp dưới hình thức khác bất kỳ Nội Dung nào xâm phạm bất kỳ bằng sáng chế, thương hiệu, bí mật thương mại, bản quyền hay độc quyền khác của bất kỳ bên nào</p>
                    <p className="mb-4">4.2.17. tải lên, đăng, gửi email, gửi hoặc cung cấp dưới hình thức khác bất kỳ tài liệu quảng cáo, quảng bá không được phép, &ldquo;thư rác,&rdquo; &ldquo;thư hàng loạt,&rdquo; &ldquo;thư dây chuyền&rdquo;, &ldquo;quảng cáo đa cấp&rdquo; hoặc bất kỳ hình thức câu kéo khác;</p>
                    <p className="mb-4">4.2.18. tải lên, đăng, gửi email, gửi hoặc cung cấp dưới hình thức khác bất kỳ tài liệu nào chứa virus, sâu, Trojan hoặc bất kỳ mã máy tính, trình tự, tập tin hay chương trình nào được thiết kế để trực tiếp hoặc gián tiếp cản trở, thao túng, làm gián đoạn, phá hủy hoặc hạn chế chức năng hay tính toàn vẹn của bất kỳ phần mềm hay phần cứng máy tính nào hay dữ liệu hoặc thiết bị viễn thông nào;</p>
                    <p className="mb-4">4.2.19. sử dụng bất kỳ phiên bản Dịch vụ đã sửa đổi, bị tấn công hoặc trái phép nào khác, bao gồm cả để gian lận, giành lợi thế không công bằng liên quan đến Người dùng khác hoặc cho bất kỳ mục đích nào khác;</p>
                    <p className="mb-4">4.2.20. làm rối loạn đến mạch đối thoại bình thường, làm cho màn hình &ldquo;cuộn&rdquo; nhanh hơn mức Người dùng Các Dịch Vụ có thể đánh máy, hoặc hành động khác theo cách ảnh hưởng tiêu cực đến khả năng tham gia trao đổi trong thời gian thực của Người dùng khác.</p>
                    <p className="mb-4">4.2.21. làm gián đoạn, thao túng hoặc làm rối loạn Các Dịch Vụ hoặc các máy chủ hay mạng được kết nối với Các Dịch Vụ hoặc việc sử dụng Các Dịch Vụ của bất kỳ Người dùng nào khác, hoặc không tuân thủ bất kỳ yêu cầu, thủ tục, chính sách hay quy định nào của các mạng được kết nối với Các Dịch Vụ;</p>
                    <p className="mb-4">4.2.22. có bất kỳ hành động nào hay liên quan đến bất kỳ hành vi nào có thể trực tiếp hay gián tiếp làm thiệt hại, vô hiệu, gây áp lực quá mức, hoặc làm suy giảm Các Dịch Vụ hoặc các dịch vụ hay các mạng được kết nối với Các Dịch Vụ;</p>
                    <p className="mb-4">4.2.23. sử dụng Các Dịch Vụ để cố tình hay vô tình vi phạm bất kỳ điều luật, quy tắc, quy định, chỉ thị, hướng dẫn, chính sách hay quy định hiện hành nào của địa phương, tiểu bang, quốc gia hoặc quốc tế bao gồm nhưng không giới hạn ở các điều luật và qui định (cho dù có hiệu lực pháp luật hay không) liên quan đến chống rửa tiền hoặc chống khủng bố;</p>
                    <p className="mb-4">4.2.24. sử dụng Các Dịch Vụ để cung cấp sự hỗ trợ vật chất hoặc nguồn lực (hoặc để che giấu hay ngụy trang bản chất, địa điểm, nguồn gốc, hoặc quyền sở hữu đối với sự hỗ trợ vật chất hay nguồn lực) cho bất kỳ tổ chức nào bị chính phủ Hoa Kỳ xem là một tổ chức khủng bố nước ngoài tuân theo mục 219 của Luật Nhập Cư và Quốc Tịch;</p>
                    <p className="mb-4">4.2.25. thực hiện, kích hoạt, gây ra hoặc cho phép, bất kỳ giao dịch nào (bao gồm cả thanh toán hoặc giao dịch tài chính) mà bạn không được cấp phép;</p>
                    <p className="mb-4">4.2.25. tạo, truy cập hoặc sử dụng nhiều Tài khoản đối với bất kỳ Trò chơi hoặc Dịch vụ đơn lẻ nào</p>
                    <p className="mb-4">4.2.26. cố gắng bán hoặc chuyển Tài khoản của bạn hoặc bất kỳ Đơn vị ảo liên quan và/hoặc Vật phẩm ảo nào cho bất kỳ bên thứ ba nào theo bất kỳ cách nào</p>
                    <p className="mb-4">4.2.27. sử dụng Dịch vụ để vi phạm quyền riêng tư của người khác hoặc để &rdquo;theo dõi&rdquo; hoặc quấy rối người khác</p>
                    <p className="mb-4">4.2.28. tạo điều kiện hoặc khuyến khích bất kỳ vi phạm nào đối với các Điều Khoản</p>
                    <p className="mb-4">4.2.29. Dịch vụ này hoặc các chính sách khác của chúng tôi, bao gồm Chính sách Bảo mật, được sửa đổi theo thời gian; và/hoặc</p>
                    <p className="mb-4">4.2.30. sử dụng Dịch vụ để thu thập hoặc lưu trữ dữ liệu cá nhân về Người dùng khác liên quan đến các hành vi và hoạt động bị cấm được nêu ở trên.</p>
                    <p className="mb-4">4.3. Bạn hiểu rằng mọi Nội Dung, cho dù được đăng công khai hay gửi riêng tư, là do người gửi Nội Dung đó hoàn toàn chịu trách nhiệm. Điều này có nghĩa là bạn, chứ không phải Vivabyte, hoàn toàn chịu trách nhiệm đối với mọi Nội Dung bạn tạo ra, tải lên, đăng, gửi email, gửi, truyền đạt hoặc cung cấp theo hình thức khác thông qua Các Dịch Vụ. Vivabyte không kiểm soát Nội Dung đăng thông qua Các Dịch Vụ và, như thế, không đảm bảo tính chính xác, tính toàn vẹn, chất lượng hay tính hợp pháp của Nội Dung đó. Bạn hiểu rằng bằng việc sử dụng Các Dịch Vụ, bạn có thể tiếp xúc với Nội Dung mà bạn có thể cho là khiếm nhã, đáng lên án hoặc có tính công kích. Nếu bạn tin rằng bất kỳ Nội Dung nào vi phạm Điều Khoản Dịch vụ (bao gồm cả đoạn 4.2 ở trên), vui lòng thông báo cho chúng tôi ngay lập tức tại didauday@gmail..com. Chúng tôi sẽ nỗ lực hợp lý để xóa Nội Dung phản cảm bị khiếu nại trong một thời gian hợp lý theo luật hiện hành. Tuy nhiên, trong mọi trường hợp, Vivabyte sẽ không chịu trách nhiệm pháp lý dưới bất kỳ hình thức nào đối với bất kỳ Nội Dung nào, bao gồm, nhưng không giới hạn, lỗi hay thiếu sót trong bất kỳ Nội Dung nào, hay bất kỳ tổn thất hay thiệt hại nào dưới bất kỳ hình thức nào phát sinh từ việc sử dụng hoặc dựa vào bất kỳ Nội Dung nào được đăng tải, email, truyền tải hoặc cung cấp thông qua Các Dịch Vụ.</p>
                    <p className="mb-4">4.4. Trong trường hợp Tài Khoản của bạn bị xóa hoặc vô hiệu hóa theo Điều Khoản 4.4 trước đó, tất cả Đơn vị ảo và Vật phẩm ảo (như được định nghĩa bên dưới) trong Tài Khoản của bạn sẽ bị tịch thu và sẽ không được hoàn lại khoản tiền tương đương ở mức tối đa được pháp luật cho phép.</p>
                    <p className="mb-4">4.5. Bạn xác nhận và đồng ý rằng Vivabyte có thể truy cập, bảo lưu và tiết lộ thông tin tài khoản của bạn và Nội Dung của bạn nếu luật quy định điều đó hoặc tuân theo lệnh của tòa hoặc theo yêu cầu của bất kỳ cơ quan chính phủ hay cơ quan quản lý nào có thẩm quyền đối với Vivabyte hoặc vì thiện chí cho rằng sự bảo lưu truy cập hay tiết lộ đó là cần thiết một cách hợp lý để: (a) tuân thủ quy trình pháp lý; (b) thực thi các Điều Khoản Dịch Vụ này; (c) phản hồi một đơn khiếu kiện cho rằng Nội Dung vi phạm quyền của các bên thứ ba; (d) phản hồi yêu cầu của bạn đối với dịch vụ chăm sóc khách hàng; hoặc (e) bảo vệ quyền lợi, tài sản hoặc sự an toàn cá nhân của Vivabyte, người dùng của của Vivabyte và/hoặc công chúng.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">5. CÁC BẢN CẬP NHẬT VÀ BẢN VÁ PHẦN MỀM</h2>
                    <p className="mb-4">5.1. Các bản cập nhật và bản vá phần mềm phải được cài đặt để bạn tiếp tục chơi các Trò chơi của chúng tôi đúng cách. Chúng tôi có thể cập nhật, vá hoặc thay đổi Phần mềm. Chúng tôi có thể cập nhật, vá hoặc sửa đổi Phần mềm từ xa và truy cập Phần mềm được cài đặt trên máy hoặc thiết bị của bạn cho mục đích này và bạn cấp cho Vivabyte quyền triển khai và áp dụng các bản vá, cập nhật và sửa đổi này. Tất cả các quy định trong Điều Khoản dịch vụ này khi đề cập đến “Phần mềm” cũng bao gồm tất cả các bản vá, bản cập nhật và sửa đổi này.</p>
                    <p className="mb-4">
                        5.2. Bạn phải luôn sử dụng phiên bản Phần mềm mới nhất bao gồm tất cả các bản cập nhật và/hoặc các bản vá lỗi do chúng tôi cung cấp và trong phạm vi tối đa được pháp luật cho phép, Vivabyte sẽ không chịu trách nhiệm về bất kỳ tổn thất hoặc thiệt hại nào phát sinh do bạn không sử dụng phiên bản mới nhất phiên bản hoặc việc bạn sử dụng bất kỳ phiên bản Phần mềm lỗi thời nào.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">6. TÀI KHOẢN VÀ BẢO MẬT</h2>
                    <p className="mb-4">6.1. Một số chức năng trong Các Dịch Vụ của chúng tôi yêu cầu phải đăng ký một Tài Khoản bằng cách chọn danh định người dùng duy nhất (&ldquo;ID Người Dùng&rdquo;) và mật khẩu, và bằng cách cung cấp một số thông tin cá nhân nhất định. Nếu bạn chọn một ID Người Dùng mà Vivabyte, theo quyết định của mình, thấy là phản cảm hoặc không thích hợp, Vivabyte có quyền đình chỉ hoặc chấm dứt Tài Khoản của bạn.</p>
                    <p className="mb-4">
                        6.2. Tài Khoản của bạn không thể chuyển nhượng và chỉ sử dụng cho mục đích cá nhân của bạn. Bạn không được phép cho bất kỳ bên thứ ba nào truy cập hoặc sử dụng Tài Khoản của mình cho bất kỳ mục đích nào hoặc cố gắng chuyển Tài Khoản hoặc Đơn vị ảo liên quan và/hoặc Vật phẩm ảo cho bất kỳ bên thứ ba nào theo bất kỳ cách nào.</p>
                    <p className="mb-4">6.3. Bạn có thể sử dụng Tài Khoản của mình để tiếp cận/truy cập các sản phẩm, trang web hoặc dịch vụ, ngay cả khi chúng được cung cấp bởi bên thứ ba, mà chúng tôi đã cho phép truy cập hoặc chúng tôi đã có kí kết hợp đồng, liên kết hay hợp tác. Vivabyte đã không xem xét, hay nhận trách nhiệm đối với bất kỳ nội dung, chức năng, bảo mật, dịch vụ, chính sách bảo mật nào của bên thứ ba, hay các hoạt động khác của các sản phẩm, trang web hoặc dịch vụ đó. Trong trường hợp đó, điều khoản dịch vụ dành cho những sản phẩm, website, dịch vụ đó, gồm cả chính sách bảo mật tương ứng, vẫn được áp dụng khi bạn sử dụng sản phẩm, website, dịch vụ đó.</p>
                    <p className="mb-4">
                        6.4. Bạn đồng ý (a) bảo mật mật khẩu của bạn và chỉ sử dụng ID Người Dùng và mật khẩu của bạn khi đăng nhập, (b) đảm bảo rằng bạn đăng xuất ra khỏi tài khoản của mình vào cuối mỗi phiên truy cập, (c) thông báo ngay cho Vivabyte biết bất kỳ trường hợp nào sử dụng trái phép ID Người Dùng và/hoặc mật khẩu của bạn hoặc bất kỳ vi phạm nào khác về bảo mật hoặc không tuân thủ Điều Khoản dịch vụ này hoặc luật hiện hành, và (d) đảm bảo rằng thông tin Tài Khoản của bạn là chính xác và cập nhật. Bạn hoàn toàn chịu trách nhiệm đối với mọi hoạt động diễn ra dưới tên ID Người Dùng và Tài Khoản của bạn ngay cả khi các hoạt động hay việc sử dụng đó không phải do bạn thực hiện. Vivabyte sẽ không chịu trách nhiệm pháp lý đối với bất kỳ tổn thất hay thiệt hại nào phát sinh từ việc ID Người dùng, mật khẩu hoặc Tài Khoản của bạn bị sử dụng trái phép hoặc việc bạn không tuân thủ điều khoản này.</p>
                    <p className="mb-4">6.5. Bạn đồng ý rằng Vivabyte có thể, vì bất kỳ lý do gì, tự quyền quyết định và không cần thông báo hay chịu trách nhiệm pháp lý đối với bạn hay bất kỳ bên thứ ba nào, ngay lập tức chấm dứt Tài Khoản và ID Người Dùng của bạn, và xóa hay gỡ bỏ bất kỳ Nội Dung nào liên kết với Tài Khoản và ID Người Dùng của bạn ra khỏi Các Dịch Vụ. Căn cứ chấm dứt tài khoản có thể bao gồm, nhưng không giới hạn (a) tài khoản không hoạt động trong thời gian dài, (b) vi phạm nội dung hoặc tinh thần của các Điều Khoản Dịch Vụ này, (c) vi phạm pháp luật, (d) có hành vi gian lận, quấy rối, lăng mạ, đe dọa hoặc xúc phạm hoặc (e) hành vi có hại cho Người dùng khác, bên thứ ba, hoặc lợi ích kinh doanh hoặc danh tiếng của Vivabyte hoặc có thể khiến Vivabyte phải chịu các hành động pháp lý hoặc theo quy định. Hành vi sử dụng Tài Khoản cho mục đích phi pháp, gian lận, quấy rối, lăng mạ, đe dọa hay xúc phạm có thể bị báo cho các cơ quan thực thi pháp luật mà không cần thông báo cho bạn. Nếu bạn nộp đơn khiếu kiện (cho dù nguyên nhân kiện là gì) hoặc chống lại Vivabyte, hoặc liên quan đến Vivabyte dưới bất kỳ hình thức nào, thì Vivabyte có thể chấm dứt Tài Khoản của bạn.</p>
                    <p className="mb-4">
                        6.6. Nếu Tài Khoản của bạn không hoạt động (có nghĩa là bạn đã không đăng nhập vào hoặc sử dụng Tài Khoản của mình) quá thời hạn được quy định bởi pháp luật, Vivabyte có quyền xóa hoặc vô hiệu Tài Khoản của bạn và số Sò và tất cả các vật phẩm ảo khác trong trò chơi có trong Tài Khoản của bạn sẽ bị mất và sẽ không có khoản hoàn trả nào được thực hiện theo cùng một mức tương đương tối đa được pháp luật cho phép.</p>
                    <p className="mb-4">6.7. Bạn chỉ được sử dụng Các Dịch Vụ và/hoặc mở Tài Khoản nếu khu vực áp dụng của bạn cho phép bạn chấp nhận các Điều Khoản Dịch Vụ này.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">7. CÁC KHOẢN PHÍ VÀ THANH TOÁN</h2>
                    <p className="mb-4">7.1. Liên quan đến một số Trò chơi và các Dịch vụ khác, bạn được cung cấp tùy chọn để mua các đơn vị ảo trong trò chơi (“Đơn vị ảo”), vật phẩm hoặc skin ảo trong trò chơi (“Vật phẩm ảo”) hoặc các quyền khác có sẵn thông qua Dịch vụ. Tùy thuộc vào quyền tài phán của bạn và Dịch vụ bạn chọn mua, đôi khi bạn có thể thanh toán cho chúng tôi hoặc cho các bên thứ ba khác</p>
                    <p className="mb-4">7.2. Nếu bạn chọn thực hiện các giao dịch mua như vậy hoặc nếu không thì phải chịu các khoản phí liên quan đến việc sử dụng Dịch vụ của bạn, bạn đồng ý thanh toán khoản phí đó để nhận Đơn vị ảo hoặc để nhận quyền truy cập và/hoặc nhận quyền lợi của Các Dịch Vụ đó. Giá dành cho Đơn vị ảo và Các Dịch Vụ không bao gồm các khoản thuế hiện hành và phí đổi tiền, trừ trường hợp qui định khác. Bạn hoàn toàn chịu trách nhiệm đóng các khoản thuế hay phí khác đó. Chúng tôi có thể đình chỉ hoặc hủy bất kỳ giao dịch và/hoặc quyền truy cập của bạn vào Các Dịch Vụ nếu chúng tôi không nhận được thanh toán đầy đủ từ bạn trong thời hạn thanh toán quy định. Việc đình chỉ hoặc hủy Các Dịch Vụ vì không thanh toán có thể dẫn đến mất quyền truy cập và sử dụng Tài Khoản của bạn và Nội Dung của nó.</p>
                    <p className="mb-4">7.3. Nói chung, để thanh toán các khoản phí cho bất kỳ Đơn vị ảo, Vật phẩm ảo hoặc Dịch vụ nào khác, bạn sẽ được yêu cầu chọn phương thức thanh toán trước khi hoàn tất giao dịch mua của mình hoặc tại thời điểm bạn bắt đầu thực hiện đăng ký Dịch vụ đó. Các khoản thanh toán cho Đơn vị ảo, Vật phẩm ảo hoặc các Dịch vụ khác cũng có thể được xử lý thông qua các nhà cung cấp dịch vụ thanh toán bên thứ ba. Trong những trường hợp như vậy, việc mua Đơn vị ảo, Vật phẩm ảo hoặc các Dịch vụ khác từ các bên thứ ba đó hoặc thông qua các nhà cung cấp dịch vụ thanh toán của bên thứ ba đó chịu sự điều chỉnh của các điều khoản và điều kiện, chính sách bảo mật tương ứng của họ. và luật hiện hành của khu vực tài phán nơi các giao dịch mua đó được thực hiện.</p>
                    <p className="mb-4">
                        7.4. Nếu có thể, bạn có thể truy cập và thay đổi thông tin tài khoản thanh toán và phương thức thanh toán của mình bất kỳ lúc nào. Bạn đồng ý cho phép Vivabyte sử dụng bất kỳ thông tin tài khoản cập nhật nào liên quan đến phương thức thanh toán do ngân hàng phát hành hoặc mạng thanh toán hiện hành của bạn cung cấp. Bạn đồng ý luôn cập nhật thông tin tài khoản thanh toán của mình. Các thay đổi mà bạn thực hiện đối với tài khoản thanh toán của mình sẽ không ảnh hưởng đến các khoản phí mà chúng tôi gửi đến tài khoản thanh toán của bạn trước khi chúng tôi có thể thực hiện một cách hợp lý các thay đổi của bạn.</p>
                    <p className="mb-4">7.5. Bằng cách cung cấp cho Vivabyte hoặc bên thứ ba cung cấp dịch vụ thanh toán tương ứng một phương thức thanh toán hoặc mua bất kỳ Đơn vị ảo, Vật phẩm ảo hoặc Dịch vụ nào khác, bạn:</p>
                    <p className="mb-4">7.5.1. đảm bảo rằng bạn được phép sử dụng phương thức thanh toán mà bạn đã cung cấp và rằng bất kỳ thông tin thanh toán nào bạn cung cấp đều là đúng sự thực và chính xác;</p>
                    <p className="mb-4">
                        7.5.2. ủy quyền cho Vivabyte hoặc bên thứ ba cung cấp dịch vụ thanh toán tương ứng tính phí cho bạn đối với Đơn vị ảo có liên quan, Vật phẩm ảo hoặc các Dịch vụ khác mà bạn mua bằng phương thức thanh toán ưa thích của bạn;</p>
                    <p className="mb-4">
                        7.5.3. cho phép Vivabyte hoặc bên thứ ba cung cấp dịch vụ thanh toán tương ứng tính phí cho bạn đối với bất kỳ tính năng có trả phí nào của Các Dịch Vụ mà bạn lựa chọn đăng ký hoặc sử dụng trong thời gian các Điều Khoản Dịch Vụ này có hiệu lực.</p>
                    <p className="mb-4">7.6. Tùy thuộc vào bản chất của giao dịch mua và tùy thuộc vào luật hiện hành, chúng tôi có thể lập hóa đơn cho bạn (a) trước; (b) tại thời điểm mua hàng; hoặc (c) định kỳ đối với Dịch vụ dựa trên đăng ký.</p>
                    <p className="mb-4">7.7. Chúng tôi có thể thay đổi giá của Đơn vị ảo, Vật phẩm ảo và/hoặc bất kỳ Dịch vụ nào vào bất kỳ lúc nào. Nếu có thời hạn và giá cố định cho ưu đãi Dịch vụ của bạn, thì giá đó sẽ vẫn có hiệu lực trong suốt thời hạn nêu trên.</p>
                    <p className="mb-4">7.8. Quyền sử dụng bất kỳ Đơn vị ảo hoặc Vật phẩm ảo nào của bạn là giấy phép có giới hạn, không độc quyền, không thể chuyển nhượng, không thể cấp phép lại, có thể thu hồi để sử dụng Đơn vị ảo và Vật phẩm ảo đó chỉ cho việc sử dụng Các Dịch Vụ với mục đích giải trí cá nhân và mục đích phi thương mại của bạn. Sau khi mua, mọi Đơn vị ảo hoặc Vật phẩm ảo đã mua sẽ có giá trị vô thời hạn trừ khi được sử dụng hoặc đổi hết trong Dịch vụ, cho đến khi Tài Khoản của bạn bị chấm dứt vì bất kỳ lý do gì hoặc nếu chúng tôi không còn có thể cung cấp dịch vụ hợp pháp cho Tài Khoản của bạn (ví dụ: nếu bạn rút lại sự cho phép cho phép chúng tôi sử dụng dữ liệu cá nhân của bạn). Nếu Tài Khoản của bạn không hoạt động hoặc duy trì trạng thái không hoạt động (có nghĩa là bạn đã không đăng nhập vào Tài Khoản của mình) trong hơn 6 tháng, Vivabyte có quyền xóa hoặc hủy kích hoạt Tài Khoản của bạn và tất cả Đơn vị ảo và Vật phẩm ảo trong Tài Khoản của bạn sẽ bị hủy bỏ theo Điều 6.6 như trên.</p>
                    <p className="mb-4">7.9. Đơn vị ảo và Vật phẩm ảo không có giá trị tiền tệ và không có giá trị bên ngoài Dịch vụ. Đơn vị ảo không được bán, mua bán, chuyển nhượng, quy đổi hoặc đổi lấy tiền mặt hoặc hàng hóa hoặc dịch vụ khác ngoài Trò chơi và Dịch vụ. Đơn vị ảo chỉ có thể được quy đổi cho Vật phẩm ảo hoặc các quyền khác có sẵn thông qua Trò chơi và Dịch vụ của chúng tôi.</p>
                    <p className="mb-4">7.10. Trừ khi luật hiện hành hoặc các điều khoản dịch vụ cụ thể của ưu đãi Dịch vụ có quy định khác, tất cả các giao dịch mua Đơn vị ảo, Vật phẩm ảo hoặc các Dịch vụ khác là cuối cùng và không được hoàn lại. Sau khi bạn đổi bất kỳ Đơn vị ảo nào để lấy Vật phẩm ảo hoặc quyền lợi khác, Vật phẩm ảo đó hoặc quyền lợi khác là quyền cuối cùng và không thể trả lại, trao đổi hoặc hoàn lại. Bạn có thể hủy bất kỳ Dịch vụ nào bất kỳ lúc nào, nhưng tất cả các khoản thanh toán trước và tất cả các giao dịch mua bất kỳ Đơn vị ảo, Vật phẩm Ảo hoặc Dịch vụ nào khác đều không được hoàn lại. Nếu bạn thực hiện giao dịch mua hàng như vậy từ bên thứ ba được ủy quyền hoặc thực hiện thanh toán qua nhà cung cấp dịch vụ thanh toán bên thứ ba, bạn cũng có thể cần tham khảo các điều khoản và điều kiện tương ứng của các bên thứ ba đó để biết thêm thông tin về chính sách hoàn tiền tương ứng của họ.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">8. LOẠI TRỪ TRÁCH NHIỆM</h2>
                    <p className="mb-4">8.1. CÁC DỊCH VỤ ĐƯỢC CUNG CẤP THEO &ldquo;NGUYÊN TRẠNG&rdquo; VÀ KHÔNG CÓ BẤT KỲ SỰ ĐẢM BẢO, KHẲNG ĐỊNH HAY CAM ĐOAN NÀO CỦA Vivabyte DƯỚI BẤT KỲ HÌNH THỨC NÀO, THÀNH VĂN, BẤT THÀNH VĂN HAY THEO PHÁP ĐỊNH VỀ CÁC DỊCH VỤ, BAO GỒM NHƯNG KHÔNG GIỚI HẠN Ở ĐẢM BẢO CHẤT LƯỢNG, HIỆU SUẤT, KHÔNG VI PHẠM, TÍNH KHẢ MẠI, HAY TÍNH PHÙ HỢP CHO MỘT MỤC ĐÍCH CỤ THỂ, CŨNG KHÔNG CÓ BẤT KỲ SỰ ĐẢM BẢO NÀO ĐƯỢC TẠO RA BỞI QUÁ TRÌNH GIAO DỊCH, THỰC HIỆN HAY SỬ DỤNG THƯƠNG MẠI. KHÔNG GIỚI HẠN Ở NỘI DUNG BÊN TRÊN, Vivabyte KHÔNG ĐẢM BẢO RẰNG CÁC DỊCH VỤ NÀY HOẶC CÁC CHỨC NĂNG TRONG CÁC DỊCH VỤ ĐÓ SẼ LÀ KHẢ DỤNG, CÓ THỂ TRUY CẬP, KHÔNG BỊ GIÁN ĐOẠN, KỊP THỜI, AN TOÀN, CHÍNH XÁC, HOÀN CHỈNH HAY KHÔNG CÓ LỖI, RẰNG CÁC KHIẾM KHUYẾT, NẾU CÓ, SẼ ĐƯỢC KHẮC PHỤC, HAY RẰNG TRANG WEB NÀY VÀ/HOẶC MÁY CHỦ CUNG CẤP TRANG WEB NÀY LÀ KHÔNG CÓ VIRUS, ĐỒNG HỒ, HẸN GIỜ, BỘ ĐẾM, S U, KHÓA PHẦN MỀM, THIẾT BỊ DROP DEAD, TROJAN, ĐỊNH TUYẾN, TRAP DOOR, BOM HẸN GIỜ HOẶC BẤT KỲ MÃ, CHỈ THỊ, CHƯƠNG TRÌNH HAY THÀNH PHẦN CÓ HẠI NÀO KHÁC. BẠN XÁC NHẬN RẰNG TOÀN BỘ RỦI RO PHÁT SINH NGOÀI VIỆC SỬ DỤNG HOẶC HIỆU SUẤT DỊCH VỤ ĐƯỢC XỬ LÝ VỚI BẠN ĐỐI VỚI MỨC ĐỘ TỐI ĐA ĐƯỢC PHÁP LUẬT CHO PHÉP.</p>
                    <p className="mb-4">8.2. Một số khu vực không cho phép loại trừ trách nhiệm đối với những bảo đảm bất thành văn, do đó một số hoặc tất cả tuyên bố loại trừ bên trên có thể không áp dụng cho bạn trong phạm vi chúng bị loại trừ bởi luật hiện hành</p>
                    <p className="mb-4">8.3. Vivabyte sẽ không chịu trách nhiệm về bất kỳ tổn thất hoặc thiệt hại nào hoặc việc không tuân thủ hoặc chậm trễ trong việc tuân thủ các nghĩa vụ của chúng tôi theo Điều Khoản Dịch vụ này do bất kỳ sự kiện hoặc trường hợp nào nằm ngoài tầm kiểm soát hợp lý của chúng tôi gây ra trực tiếp hoặc gián tiếp, bao gồm cả do lỗi hệ thống, mạng sự cố, trục trặc kỹ thuật hoặc mất dữ liệu do bất kỳ lý do nào trước đây, tác động của thiên tai, lũ lụt, dịch bệnh, đại dịch, kiểm dịch, bạo loạn hoặc chiến tranh.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">9.
                        CÁC TRƯỜNG HỢP LOẠI TRỪ VÀ GIỚI HẠN TRÁCH NHIỆM PHÁP LÝ</h2>
                    <p className="mb-4">9.1. TRONG MỌI TRƯỜNG HỢP, Vivabyte SẼ KHÔNG CHỊU TRÁCH NHIỆM PHÁP LÝ, DÙ LÀ DƯỚI HÌNH THỨC HỢP ĐỒNG, BẢO ĐẢM, LỖI DO SƠ SUẤT (DÙ LÀ CHỦ ĐỘNG, BỊ ĐỘNG HAY QUY GÁN), TRÁCH NHIỆM ĐỐI VỚI SẢN PHẨM HAY TRÁCH NHIỆM PHÁP LÝ HAY NGUYÊN NHÂN KHÁC), HOẶC NGUYÊN NH N TỐ TỤNG THEO LUẬT ĐỊNH, LUẬT LỆ, ĐỐI VỚI VIỆC MẤT QUYỀN SỬ DỤNG, MẤT LỢI NHUẬN, DOANH THU, UY TÍN HOẶC TIẾT KIỆM DỰ KIẾN HOẶC ĐỐI VỚI BẤT KỲ THIỆT HẠI GIÁN TIẾP, VÔ TÌNH, ĐẶC BIỆT HAY HẬU QUẢ NÀO (BAO GỒM NHƯNG KHÔNG GIỚI HẠN Ở MẤT DỮ LIỆU, GIÁN ĐOẠN DỊCH VỤ, LỖI MÁY TÍNH, ĐIỆN THOẠI DI ĐỘNG HAY THIẾT BỊ DI ĐỘNG) PHÁT SINH TỪ HOẶC LIÊN QUAN ĐẾN VIỆC SỬ DỤNG HAY KHÔNG THỂ SỬ DỤNG TRANG WEB NÀY HOẶC CÁC DỊCH VỤ, BAO GỒM, NHƯNG KHÔNG GIỚI HẠN, BẤT KỲ THIỆT HẠI NÀO PHÁT SINH TỪ ĐÓ, NGAY CẢ KHI Vivabyte ĐÃ ĐƯỢC THÔNG BÁO VỀ KHẢ NĂNG XẢY RA NHỮNG THIỆT HẠI ĐÓ.</p>
                    <p className="mb-4">9.2. QUYỀN DUY NHẤT CỦA BẠN LIÊN QUAN ĐẾN CÁC SỰ CỐ HOẶC SỰ KHÔNG HÀI LÒNG NÀO VỚI CÁC DỊCH VỤ LÀ CHẤM DỨT TÀI KHOẢN CỦA BẠN VÀ NGƯNG SỬ DỤNG CÁC DỊCH VỤ.</p>
                    <p className="mb-4">9.3. BẤT KỂ CÁC PHẦN TRƯỚC, TRỪ TRƯỜNG HỢP Vivabyte BỊ TÒA ÁN CÓ THẨM QUYỀN TUYÊN LÀ PHẢI CHỊU TRÁCH NHIỆM PHÁP LÝ (ĐỐI VỚI LỖI BẤT CẨN HIỂN NHIÊN), TRÁCH NHIỆM PHÁP LÝ CỦA Vivabyte ĐỐI VỚI BẠN HOẶC ĐỐI VỚI BẤT KỲ BÊN THỨ BA NÀO KHÁC CHỈ GIỚI HẠN Ở MỨC DƯỚI 2.000.000 VNĐ (HAI TRIỆU ĐỒNG CHẴN).</p>
                    <p className="mb-4">9.4. KHÔNG CÓ NỘI DUNG NÀO CỦA CÁC ĐIỀU KHOẢN DỊCH VỤ NÀY SẼ HẠN CHẾ HAY LOẠI TRỪ BẤT KỲ TRÁCH NHIỆM PHÁP LÝ NÀO ĐỐI VỚI TRƯỜNG HỢP TỬ VONG HOẶC THƯƠNG TẬT GÂY RA BỞI SỰ BẤT CẨN CỦA Vivabyte, ĐỐI VỚI SỰ GIAN LẬN HOẶC ĐỐI VỚI BẤT KỲ TRÁCH NHIỆM PHÁP LÝ NÀO KHÁC MÀ KHÔNG THỂ HẠN CHẾ VÀ/HOẶC LOẠI TRỪ MỘT CÁCH HỢP PHÁP.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">10. LIÊN KẾT ĐẾN CÁC TRANG CỦA BÊN THỨ BA</h2>
                    <p className="mb-4">10.1. Một số đường dẫn cụ thể được cung cấp thông qua Các Dịch Vụ sẽ đưa người dùng rời khỏi Trang Web hoặc các Trò chơi. Các đường dẫn này chỉ mang tính tham khảo, và các trang mà chúng liên kết đến không thuộc quyền kiểm soát của Vivabyte dưới bất kỳ hình thức nào và do đó bạn tự chịu rủi ro khi truy cập các trang đó. Do đó, Vivabyte không chịu trách nhiệm dưới bất kỳ hình thức nào đối với nội dung của bất kỳ trang web bên thứ ba nào hoặc bất kỳ liên kết nào có trong một trang được liên kết bao gồm bất kỳ thay đổi hay cập nhật nào đối với các trang đó. Vivabyte cung cấp các liên kết này ở đây chỉ nhằm mục đích thuận tiện cho bạn, và việc bao gồm bất kỳ liên kết nào không ngụ ý hay bày tỏ dưới bất kỳ hình thức nào về sự liên kết, ủng hộ hay tài trợ của Vivabyte đối với bất kỳ trang web nào được liên kết và/hoặc bất kỳ nội dung nào của nó trong đó. Chúng tôi không chịu trách nhiệm về bất kỳ tổn thất hoặc tổn hại nào xảy ra cho bạn do kết quả của các trang web đó.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">11. NHỮNG ĐÓNG GÓP CỦA BẠN ĐỐI VỚI CÁC DỊCH VỤ</h2>
                    <p className="mb-4">11.1. Bằng việc gửi Nội Dung để đưa vào Các Dịch Vụ, bạn đảm bảo và cam đoan rằng bạn có mọi sự cho phép cần thiết để cấp quyền sử dụng dưới đây cho Vivabyte. Bạn xác nhận và đồng ý thêm rằng bạn hoàn toàn chịu trách nhiệm cá nhân đối với bất kỳ nội dung mà bạn đăng hoặc cung cấp trên hoặc thông qua Các Dịch Vụ, bao gồm nhưng không giới hạn, tính chính xác, độ tin cậy, tính phù hợp với các quy định pháp luật và các giới hạn pháp lý đối với bất kỳ nội dung nào đã được đăng tải bởi bạn. Qua đây, bạn cấp cho Vivabyte và các bên kế thừa của họ quyền sử dụng không hủy ngang, trên toàn cầu, không độc quyền, không tính phí bản quyền, có thể chuyển giao, để sử dụng, sao chép, phát tán, tái xuất bản, gửi, điều chỉnh, sửa đổi, phái sinh, hiển thị công khai, thực hiện công khai sự đóng góp về Nội Dung đó trên, thông qua hoặc liên quan đến Các Dịch Vụ dưới bất kỳ hình thức phương tiện nào và thông qua bất kỳ kênh truyền thông nào, bao gồm, nhưng không giới hạn phục vụ cho mục đích quảng bá và tái phân phối một phần của Các Dịch Vụ (và các bản phái sinh) và cho bất kỳ mục đích thương mại hoặc kinh doanh nào khác. Bạn hiểu rằng sự đóng góp của bạn có thể được gửi qua các hệ thống mạng khác nhau và được sửa đổi để phù hợp và thích ứng với các yêu cầu kỹ thuật.</p>
                    <p className="mb-4">
                        11.2. Bất kỳ tài liệu, thông tin, ý tưởng hay Nội Dung nào khác mà bạn đăng trên hoặc thông qua Các Dịch Vụ, hoặc gửi theo cách khác cho Vivabyte dưới bất kỳ hình thức nào (mỗi trường hợp được gọi là &ldquo;Thông Tin Gửi”), không được Vivabyte xem là thông tin mật và có thể được Vivabyte hoặc các công ty liên kết phát tán hoặc sử dụng mà không trả thù lao hay chịu trách nhiệm pháp lý đối với bạn vì bất kỳ mục đích nào, bao gồm, nhưng không giới hạn cả việc phát triển, sản xuất và tiếp thị sản phẩm. Bằng việc cung cấp Thông Tin Gửi cho Vivabyte, bạn xác nhận và đồng ý rằng Vivabyte và/hoặc các bên thứ ba khác có thể phát triển phần mềm, ứng dụng, giao diện, sản phẩm và các bản điều chỉnh và cải tiến của những nội dung đó một cách độc lập, có chức năng, mã giống hoặc tương tự hoặc các đặc điểm khác với các ý tưởng được nêu ra trong Thông Tin Gửi của bạn. Theo đó, bạn cấp cho Vivabyte và các bên kế thừa của họ quyền không rút lại, trên toàn cầu, không độc quyền, không tính tác quyền, có thể cấp quyền thứ cấp và có thể chuyển nhượng để phát triển các hạng mục nói trên, và sử dụng, sao chép, phát tán, tái xuất bản, gửi, điều chỉnh, sửa đổi, tạo phó bản, trưng bày công khai, và trình diễn công khai bất kỳ Thông Tin Gửi nào trên, thông qua hoặc liên quan đến Các Dịch Vụ ở bất kỳ hình thức phương tiện nào và thông qua bất kỳ kênh truyền thông nào, bao gồm cả việc quảng bá và tái phân phối một phần của Các Dịch Vụ (và bản phái sinh). Quyền được cấp cho bạn sẽ tiếp tục có hiệu lực đến khi nào Vivabyte quyết định sử dụng Thông Tin Gửi của bạn. Quy định này không áp dụng cho thông tin cá nhân tuân theo chính sách bảo mật của chúng tôi trừ trường hợp bạn công khai thông tin cá nhân đó trên hoặc thông qua Các Dịch Vụ.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">12. CÁC ĐÓNG GÓP CỦA BÊN THỨ BA ĐỐI VỚI CÁC DỊCH VỤ VÀ CÁC LIÊN KẾT BÊN NGOÀI</h2>
                    <p className="mb-4">
                        12.1. Mỗi nội dung nào đóng góp cho Các Dịch Vụ thể hiện dưới dạng dữ liệu, tin nhắn, hình ảnh, âm thanh, video, phần mềm hoặc các Nội Dung khác, bạn sẽ chịu trách nhiệm về mức độ chính xác, tin cậy, rõ ràng cũng như tính phù hợp với qui định pháp luật và giới hạn pháp lý đối với bất kỳ nội dung mà họ đã đóng góp. Như vậy, Vivabyte không chịu trách nhiệm và cũng sẽ không kiểm tra, giám sát độ chính xác, tin cậy, tính nguyên gốc, quyền liên quan, tính hợp pháp và các giới hạn pháp lý có liên quan đến các nội dung bạn đóng góp. Vivabyte sẽ không phải chịu trách nhiệm đối với các hoạt động hoặc tạm ngừng hoạt động của Người dùng kể cả các nội dung họ post hoặc tạo sẵn qua Dịch Vụ.</p>
                    <p className="mb-4">
                        12.2. Ngoài ra, Các Dịch Vụ có thể chứa các liên kết đến thông tin mới bằng văn bản và video của bên thứ ba (và podcast) (gọi chung là &ldquo;thông tin mới của bên thứ ba&rdquo;), các sản phẩm, trang web, dịch vụ và chương trình khuyến mãi, hoặc liên kết đến các ứng dụng phần mềm của bên thứ ba. Ngoài ra, các bên thứ ba có thể cung cấp, trên trang web của chính họ, các thông tin mới của bên thứ ba, và ứng dụng phần mềm. Các liên kết bên thứ ba, thông tin mới của bên thứ ba, sản phẩm, trang web, dịch vụ và ứng dụng phần mềm nào không thuộc sở hữu hay kiểm soát của Vivabyte. Đúng hơn, chúng được vận hành bởi, và là tài sản của nhiều bên thứ ba khác nhau, và có thể được bảo hộ bởi các điều luật và hiệp ước về bảo hộ bản quyền hoặc sở hữu trí tuệ khác. Vivabyte đã không xem xét hay chịu trách nhiệm đối với bất kỳ nội dung, chức năng, bảo mật, dịch vụ, chính sách về quyền riêng tư nào, hay các hoạt động khác của các bên thứ ba đó. Bạn nên đọc các điều khoản và các chính sách khác được công bố bởi các bên thứ ba đó trên trang web của họ hoặc nơi khác. Bằng việc sử dụng Các Dịch Vụ, bạn đồng ý rằng Vivabyte sẽ không chịu trách nhiệm pháp lý dưới bất kỳ hình thức nào từ việc sử dụng hay không thể sử dụng bảng tin, trang web hay ứng dụng con của bất kỳ bên thứ ba nào. Bạn xác nhận và đồng ý thêm rằng Vivabyte có thể vô hiệu việc sử dụng của bạn, hoặc gỡ bỏ, bất kỳ liên kết nào của bên thứ ba, thông tin mới, hay ứng dụng của bên thứ ba trên Các Dịch Vụ ở mức độ chúng vi phạm các Điều Khoản Dịch Vụ này.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">
                        13.
                        VI PHẠM CÁC ĐIỀU KHOẢN DỊCH VỤ CỦA CHÚNG TÔI</h2>
                    <p className="mb-4">
                        13.1. Nếu bạn cho rằng một Người dùng trên Trang Web của chúng tôi đang vi phạm các Điều Khoản Dịch Vụ này, vui lòng liên hệ với didauday@gmail.com. </p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">
                        14. KHIẾU NẠI VỀ XÂM PHẠM BẢN QUYỀN</h2>
                    <p className="mb-4">
                        14.1. Nếu bạn cho rằng tác phẩm của bạn (như được đưa vào Các Dịch Vụ) đã bị sao chép, trưng bày, hoặc phát tán theo cách cấu thành hành vi xâm phạm bản quyền, vui lòng thông báo cho Đại Diện Bảo Vệ Bản Quyền của chúng tôi.</p>
                    <p className="mb-4">
                        14.2. Thông báo về hành vi xâm phạm bản quyền phải được thể hiện bằng văn bản như các quy định đề cập dưới đây và về cơ bản phải gồm có các nội dung sau đây: (a) chữ ký tay hoặc chữ ký điện tử của người được ủy quyền thay mặt cho chủ sở hữu của đối tượng bị xâm phạm bản quyền ; (b) bản mô tả (các) tác phẩm có bảo hộ bản quyền đó và chỉ dẫn về nội dung nào trong tác phẩm đó được cho là bị xâm phạm bản quyền (c) bản mô tả tên chính xác của tác phẩm xâm phạm và vị trí của tác phẩm xâm phạm trên Các Dịch Vụ; (d) thông tin cần thiết để Vivabyte có thể liên hệ với bạn, chẳng hạn như địa chỉ thực của bạn, số điện thoại và địa chỉ email của bạn; (e) tuyên bố của bạn rằng bạn có thiện chí để tin rằng việc sử dụng tài liệu theo cách mà bạn đã khiếu nại là không được sự cho phép của chủ sở hữu bản quyền, đại diện của họ, hoặc pháp luật; (f) tuyên bố của bạn rằng thông tin trong thông báo là chính xác và, bạn chịu trách nhiệm trước pháp luật nếu khai man rằng bạn được ủy quyền thay mặt chủ sở hữu bản quyền để khiếu nại. Bạn có thể liên hệ với Đại Diện Bảo Vệ Bản Quyền của Vivabyte qua email: didauday@gmail.com</p>
                    <p className="mb-4">Đại Diện Bảo Vệ Bản Quyền chỉ có thể trả lời khiếu kiện liên quan đến cáo buộc xâm phạm bản quyền.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">
                        15. ĐẢM BẢO VÀ CAM ĐOAN CỦA BẠN</h2>
                    <p className="mb-4">
                        15.1. Bạn đảm bảo và cam đoan rằng:</p>
                    <p className="mb-4">
                        15.1.1. bạn có năng lực pháp lý (và trong trường hợp sử dụng Các Dịch Vụ bởi trẻ vị thành niên, mà bạn chính là cha mẹ hoặc người giám hộ hợp pháp và đã đưa ra sự chấp thuận hợp lệ), và có quyền và khả năng ký kết các Điều Khoản Dịch Vụ này và tuân thủ các điều khoản dịch vụ này;</p>
                    <p className="mb-4">15.1.2. bạn sẽ chỉ sử dụng Các Dịch Vụ cho các mục đích hợp pháp và tuân theo các Điều Khoản Dịch Vụ này và mọi điều luật, quy định, quy tắc, chỉ thị, hướng dẫn, chính sách và quy định hiện hành;</p>
                    <p className="mb-4">15.1.3. bạn sẽ chỉ sử dụng Các Dịch Vụ trên một máy tính mà việc sử dụng đó được chủ máy tính cho phép.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">
                        16. BỒI THƯỜNG</h2>
                    <p className="mb-4">
                        16.1. Bạn đồng ý bồi thường, bảo vệ và miễn trách nhiệm cho Vivabyte, và cổ đông, công ty con, công ty liên kết, cán bộ, đại diện, những người ủy quyền, đồng sở hữu hoặc các đối tác khác và nhân viên của Vivabyte (gọi chung là &ldquo;Các Bên Được Miễn&rdquo;), bằng chi phí của bạn, từ và chống lại bất kỳ và tất cả các khiếu nại, hành động, thủ tục tố tụng, và tất cả các trách nhiệm pháp lý liên quan, thiệt hại, dàn xếp, hình phạt, tiền phạt, chi phí và phí tổn (bao gồm nhưng không giới hạn ở phí luật sư hợp lý và các chi phí giải quyết bất đồng khác) do bất kỳ Bên được bồi thường nào phát sinh của hoặc liên quan đến (a) việc lưu trữ, vận hành, quản lý và/hoặc quản lý Dịch vụ của hoặc thay mặt cho Vivabyte, (b) việc bạn vi phạm hoặc vi phạm bất kỳ điều khoản nào của Điều Khoản Dịch vụ này hoặc bất kỳ chính sách hoặc hướng dẫn nào được đề cập ở đây, (c) việc truy cập, sử dụng hoặc lạm dụng Dịch vụ của bạn, (d) bạn vi phạm bất kỳ luật hoặc quy định nào hoặc quyền của bên thứ ba, hoặc (e) xóa Tài Khoản của bạn hoặc bất kỳ Nội Dung nào mà bạn tải lên, đăng, gửi email , truyền tải hoặc nói cách khác là tạo ra một có sẵn thông qua các Dịch vụ theo Điều Khoản 4.2-4.4 ở trên.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">
                        17. TÍNH CÓ HIỆU LỰC TỪNG PHẦN</h2>
                    <p className="mb-4">
                        17.1. Nếu bất kỳ quy định nào của các Điều Khoản Dịch Vụ này bị xem là trái luật, vô hiệu, hoặc không thể thực thi vì bất kỳ lý do gì theo luật pháp của bất kỳ khu vực nào, thì quy định đó sẽ được xem là tách biệt với các Điều Khoản Dịch vụ này và sẽ không ảnh hưởng đến tính hợp lệ và khả năng thực thi của bất kỳ quy định nào còn lại trong khu vực đó hoặc tính hợp lệ hay khả năng thực thi của quy định đang bàn tới theo luật pháp của bất kỳ khu vực nào khác.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">
                        18. CÁC QUY ĐỊNH CHUNG</h2>
                    <p className="mb-4">18.1. Vivabyte bảo lưu tất cả các quyền không được cấp rõ trong đây.</p>
                    <p className="mb-4">18.2. Vivabyte có thể điều chỉnh các Điều Khoản Dịch Vụ này vào bất kỳ lúc nào bằng cách đăng các Điều Khoản Dịch Vụ đã chỉnh sửa lên Trang Web. Việc bạn tiếp tục truy cập đến hoặc sử dụng Các Dịch Vụ sau khi những thay đổi đó đã được đăng sẽ cấu thành việc bạn chấp nhận các Điều Khoản Dịch Vụ đã chỉnh sửa đó.</p>
                    <p className="mb-4">18.3. Bạn không được chuyển nhượng, cấp phép hay chuyển giao bất kỳ quyền nào đã cấp cho bạn theo đây hoặc lập hợp đồng phụ bất kỳ nghĩa vụ nào của bạn.</p>
                    <p className="mb-4">18.4. Không nội dung nào trong các Điều Khoản Dịch Vụ này sẽ cấu thành sự hợp tác, liên doanh hay quan hệ người ủy thác-đại lý giữa bạn và Vivabyte, cũng không cho phép bạn chịu bất kỳ chi phí hay trách nhiệm pháp lý nào thay mặt Vivabyte.</p>
                    <p className="mb-4">
                        18.5 Việc Vivabyte, vào bất kỳ lúc nào, không yêu cầu thực hiện bất kỳ quy định nào trong đây sẽ không ảnh hưởng dưới bất kỳ hình thức nào đến quyền của nó sau này được thực thi quy định đó trừ phi có văn bản miễn áp dụng quy định đó.</p>
                    <p className="mb-4">18.6. Các Điều Khoản Dịch Vụ này chỉ nhằm vì lợi ích của bạn và của chúng tôi và không vì lợi ích của bất kỳ cá nhân hay tổ chức nào khác, trừ các công ty liên kết với của Vivabyte.</p>
                    <p className="mb-4">
                        18.7. Các điều khoản được đặt ra trong các Điều Khoản Dịch Vụ này và bất kỳ thỏa thuận và chính xác nào được đưa vào hoặc tham chiếu trong các các Điều Khoản Dịch Vụ này cấu thành toàn bộ thỏa thuận và cam kết của các bên về Các Dịch Vụ và Trang Web này và thay thế bất kỳ thỏa thuận hay cam kết nào trước đây giữa các bên liên quan đến vấn đề đó. Các bên theo đây loại trừ tất cả các điều khoản bất thành văn. Khi ký kết thỏa thuận được tạo thành bởi các Điều Khoản Dịch Vụ này, các bên đã không dựa vào bất kỳ phát biểu, đảm bảo, cam quan, cam kết, hứa hẹn nào của bất kỳ cá nhân nào ngoài trường hợp được quy định rõ trong các Điều Khoản Dịch Vụ này. Mỗi bên khước từ, không rút lại và vô điều kiện, mọi khiếu kiện, quyền và quyền được bồi thường mà nếu không có Phần này có thể đã có liên quan đến bất kỳ quy định nào phía trên. Các Điều Khoản Dịch Vụ này có thể không được phủ nhận, giải thích hay bổ sung bởi bằng chứng của bất kỳ thỏa thuận nào trước đây, bất kỳ thỏa thuận miệng đồng thời nào hoặc bất kỳ điều khoản bổ sung nhất quán nào.</p>
                    <p className="mb-4">
                        18.8. Nếu bạn có bất kỳ thắc mắc hay quay nại nào về các Điều Khoản Dịch Vụ này hoặc bất kỳ vấn đề nào được nêu ra trong các Điều Khoản Dịch Vụ này hoặc trên Trang Web, vui lòng liên hệ với chúng tôi tại: didauday@gmail.com. </p>
                    <p className="mb-4">Cập nhật và đăng tải lần cuối: 03/11/2024 và sẽ có hiệu lực sau bảy ngày kể từ ngày đăng tải.</p>
                </section>
            </div>

            <div className="mx-auto w-full p-12 flex justify-center shadow-xl shadow-red-200 mb-20">
            </div>
        </div >
    );
}
