export default function PolicyPage() {
    return (
        <div className="w-full text-red-500">
            <div className="mx-auto w-full pt-16 px-8 md:px-32">
                <h1 className="text-4xl font-bold mb-4">CHÍNH SÁCH BẢO MẬT</h1>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">1. GIỚI THIỆU</h2>
                    <p className="mb-4">1.1. Chào mừng bạn đến với Dịch vụ của Đi Đâu Đây? được được vận hành bởi Vivabyte. Vivabyte nghiêm túc thực hiện trách nhiệm của mình liên quan đến bảo mật thông tin theo các quy định về bảo vệ bí mật thông tin cá nhân của pháp luật Việt Nam (“Luật riêng tư”) và cam kết tôn trọng quyền riêng tư và sự quan tâm của tất cả người dùng đối với trò chơi của Vivabyte (“Games”), website và ứng dụng di động của chúng tôi (“Nền tảng”) (chúng tôi nói đến Games, Nền tảng và các dịch vụ khác như được mô tả trong Điều khoản sử dụng Dịch vụ gọi chung là &ldquo;các Dịch Vụ&rdquo;). Người dùng có nghĩa là người đăng ký tài khoản với chúng tôi  hoặc người sử dụng hoặc truy cập vào các Dịch Vụ (gọi chung và gọi riêng là “Các Người Dùng”, “bạn” hoặc “của bạn”). Chúng tôi nhận biết tầm quan trọng của dữ liệu cá nhân mà bạn đã tin tưởng giao cho chúng tôi và tin rằng chúng tôi có trách nhiệm quản lý, bảo vệ và xử lý dữ liệu cá nhân của bạn một cách thích hợp. Chính sách bảo mật này (&ldquo;Chính sách bảo mật&rdquo;) được thiết kế để giúp bạn hiểu được cách thức chúng tôi thu thập, sử dụng, tiết lộ và/hoặc xử lý dữ liệu cá nhân mà bạn đã cung cấp cho chúng tôi và/hoặc lưu giữ về bạn, cho dù là hiện nay hoặc trong tương lai, cũng như để giúp bạn đưa ra quyết định sáng suốt trước khi cung cấp cho chúng tôi bất kỳ dữ liệu cá nhân nào của bạn.. Các thuật ngữ viết hoa được sử dụng trong Chính sách bảo mật này mà không được định nghĩa khác đã được giải thích trong Điều khoản Dịch vụ của Vivabyte.</p>
                    <p className="mb-4">1.2. &ldquo;Dữ Liệu Cá Nhân&rdquo; hay &ldquo;dữ liệu cá nhân&rdquo; có nghĩa là dữ liệu, dù đúng hay không, về một cá nhân mà thông qua đó có thể được xác định được danh tính, hoặc từ dữ liệu đó và thông tin khác mà một tổ chức có hoặc có khả năng tiếp cận. Các ví dụ thường gặp về dữ liệu cá nhân có thể gồm có tên, số chứng minh nhân dân và thông tin liên hệ.</p>
                    <p className="mb-4">1.3. Bằng việc sử dụng Các Dịch Vụ, đăng ký một tài khoản với chúng tôi hoặc truy cập Nền tảng, bạn xác nhận và đồng ý rằng bạn chấp nhận các phương pháp, yêu cầu, và/hoặc chính sách được mô tả trong Chính sách bảo mật này, và theo đây bạn đồng ý cho phép chúng tôi thu thập, sử dụng, tiết lộ và/hoặc xử lý dữ liệu cá nhân của bạn như mô tả trong đây. NẾU BẠN KHÔNG ĐỒNG Ý CHO PHÉP XỬ LÝ DỮ LIỆU CÁ NHÂN CỦA BẠN NHƯ MÔ TẢ TRONG CHÍNH SÁCH NÀY, VUI LÒNG KHÔNG SỬ DỤNG CÁC DỊCH VỤ CỦA CHÚNG TÔI HAY TRUY CẬP GAMES HOẶC NỀN TẢNG CỦA CHÚNG TÔI. Nếu chúng tôi thay đổi Chính sách bảo mật của mình, chúng tôi sẽ thông báo cho bạn bao gồm cả thông qua việc đăng tải những thay đổi đó hoặc Chính sách bảo mật sửa đổi trên Nền tảng của chúng tôi. Trong phạm vi pháp luật cho phép, việc tiếp tục sử dụng các Dịch Vụ hoặc Nền Tảng, bao gồm giao dịch của bạn, được xem là bạn đã công nhận và đồng ý với các thay đổi trong Chính Sách Bảo Mật này.</p>
                    <p className="mb-4">1.4. Chính sách này áp dụng cùng với các thông báo, điều khoản hợp đồng, điều khoản chấp thuận khác áp dụng liên quan đến việc chúng tôi thu thập, lưu trữ, sử dụng, tiết lộ và/hoặc xử lý dữ liệu cá nhân của bạn và không nhằm ghi đè những thông báo hoặc các điều khoản đó trừ khi chúng tôi có tuyên bố ràng khác.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">2. KHI NÀO VIVABYTE SẼ THU THẬP DỮ LIỆU CÁ NHÂN?</h2>
                    <p className="mb-4">2.1. Chúng tôi sẽ/có thể thu thập dữ liệu cá nhân về bạn:</p>
                    <ul className="mb-4 list-disc pl-5">
                        <li>Khi bạn đăng ký và/hoặc sử dụng Các Dịch Vụ, Games hoặc Nền tảng của chúng tôi, hoặc mở một tài khoản với chúng tôi;</li>
                        <li>Khi bạn gửi bất kỳ biểu mẫu nào, bao gồm đơn đăng ký hoặc các mẫu đơn khác liên quan đến bất kỳ sản phẩm và dịch vụ nào của chúng tôi, bằng hình thức trực tuyến hay dưới hình thức khác;</li>
                        <li>Khi bạn ký kết bất kỳ thỏa thuận nào hoặc cung cấp các tài liệu hoặc thông tin khác liên quan đến tương tác giữa bạn với chúng tôi, hoặc khi bạn sử dụng các sản phẩm và dịch vụ của chúng tôi;</li>
                        <li>Khi bạn tương tác với chúng tôi, chẳng hạn như thông qua các cuộc gọi điện thoại (có thể được ghi âm lại), thư từ, fax, gặp gỡ trực tiếp, các nền ứng dụng truyền thông xã hội và email; ngay cả khi bạn tương tác với các đại lý chăm sóc khách hàng của chúng tôi;</li>
                        <li>
                            Khi bạn sử dụng các dịch vụ điện tử của chúng tôi, hoặc tương tác với chúng tôi qua Games hoặc Nền tảng hoặc sử dụng Các Dịch Vụ của chúng tôi. Trường hợp này bao gồm thông qua tập tin cookie mà chúng tôi có thể triển khai khi bạn tương tác với các Games hoặc Nền tảng của chúng tôi;</li>
                        <li>Khi bạn cấp quyền trên thiết bị của bạn để chia sẻ thông tin với ứng dụng hoặc Nền tảng của chúng tôi</li>
                        <li>Khi bạn liên kết tài khoản Vivabyte với tài khoản mạng xã hội của bạn (định nghĩa bên dưới) hoặc các tài khoản bên ngoài khác hoặc sử dụng các tính năng mạng xã hội khác, phù hợp với các chính sách của nhà cung cấp</li>
                        <li>Khi bạn thực hiện các giao dịch thông qua Games hoặc Nền tảng của chúng tôi (nếu áp dụng) hoặc với các nhà cung cấp dịch vụ thanh toán bên thứ ba được ủy quyền;</li>
                        <li>Khi bạn cung cấp ý kiến phản hồi hoặc gửi khiếu nại cho chúng tôi;</li>
                        <li>Khi bạn đăng ký tham gia một cuộc thi, games hoặc các sự kiện game cụ thể; trong quá trình chơi game; và khi bạn gửi dữ liệu cá nhân của bạn cho chúng tôi vì bất kỳ lý do gì. </li>
                    </ul>
                    <p className="mb-4">Các trường hợp trên không nhằm mục đích liệt kê đầy đủ các trường hợp và chỉ đưa ra một số trường hợp phổ biến khi dữ liệu cá nhân của bạn có thể bị thu thập.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">3. VIVABYTE SẼ THU THẬP NHỮNG DỮ LIỆU GÌ?</h2>
                    <p className="mb-4">3.1. Dữ liệu cá nhân mà Vivabyte có thể thu thập bao gồm:</p>
                    <ul className="mb-4 list-disc pl-5">
                        <li>Họ tên, tên đăng nhập và ID người dùng;</li>
                        <li>Thông tin liên hệ (bao gồm địa chỉ email, số điện thoại, và/hoặc địa chỉ)</li>
                        <li>Thông tin giao dịch, bao gồm tài khoản ngân hàng và thông tin thanh toán nếu có và phù hợp với luật pháp hiện hành;</li>
                        <li>Hội thoại và các thông tin khác về những người và tài khoản mà bạn có tương tác;</li>
                        <li>
                            Giới tính, tuổi, và/ hoặc ngày tháng năm sinh;</li>
                        <li>Thông tin được gửi bởi hoặc liên quan đến (các) thiết bị được sử dụng để truy cập vào Các Dịch vụ của chúng tôi;</li>
                        <li>Hình ảnh hoặc âm thanh hoặc nội dung video mà bạn đăng lên thông qua các Dịch Vụ;</li>
                        <li>Dữ liệu về địa điểm, bao gồm địa chỉ IP;</li>
                        <li>Thông tin về nhân thân được cấp bởi chính phủ hoặc các thông tin khác mà bạn chia sẻ cho chúng tôi;</li>
                        <li>Dữ liệu truyền thông hoặc liên lạc, ví dụ như các tùy chọn nhận thông tin quảng cáo của bạn, tùy chọn phương tiện liên lạc và lịch sử thông tin liên lạc với chúng tôi, các nhà cung cấp dịch vụ của chúng tôi;</li>
                        <li>Thông tin liên quan đến câu trả lời của các cuộc khảo sát, cuộc thi hay giải đấu, và/hoặc các thông tin khác mà bạn cung cấp cho chúng tôi;</li>
                        <li>
                            Bất kỳ thông tin nào khác mà bạn cung cấp khi bạn đăng ký hay sử dụng các Dịch Vụ, bao gồm thông tin được chia sẻ qua bất ký liên kết nào với tài khoản mạng xã hội (“Tài khoản Mạng Xã hội”);</li>
                        <li>
                            Thông tin sử dụng và giao dịch, bao gồm dữ liệu về các hoạt động của bạn, các yêu cầu, việc sử dụng các Dịch Vụ và việc quảng cáo và các nội dung có liên quan khác;</li>
                    </ul>
                    <p className="mb-4">3.2. Bạn đồng ý không cung cấp cho chúng tôi bất cứ thông tin nào không chính xác hoặc gây hiểu nhầm và bạn đồng ý sẽ thông báo cho chúng tôi về bất cứ thông tin nào không chính xác hoặc khi có sự thay đổi thông tin. Theo luật hiện hành, chúng tôi bảo lưu quyền theo quyết định riêng của chúng tôi được yêu cầu các tài liệu cần thiết khác để xác minh thông tin được bạn cung cấp.</p>
                    <p className="mb-4">3.3. Nếu bạn đăng nhập để trở thành Người sử dụng các Dịch Vụ của chúng tôi sử dụng tài khoản mạng xã hội của Bạn, liên kết tài khoản của bạn với Tài khoản Mạng Xã hội của bạn hoặc sử dụng bất cứ tính năng mạng xã hội Vivabyte nào, chúng tôi có quyền truy cập thông tin về bạn mà bạn đã cung cấp một cách tự nguyên cho nhà cung cấp dịch vụ Tài khoản Mạng Xã hội của Bạn tuân theo các chính sách của các nhà cung cấp dịch vụ này, và chúng tôi sẽ quản lý và sử dụng các dữ liệu cá nhân này của bạn theo các quy định của Chính sách này tại mọi thời điểm.</p>
                    <p className="mb-4">3.4. Nếu bạn không muốn chúng tôi thu thập thông tin/dữ liệu cá nhân nói trên, bạn có thể chọn không tham gia vào bất kỳ lúc nào bằng cách thông báo bằng văn bản đến Nhân Viên Bảo Vệ Dữ Liệu của chúng tôi. Có thể tìm thấy thêm thông tin về nội dung trong mục &ldquo;Bạn có thể rút lại sự cho phép xóa tên, yêu cầu truy cập hoặc điều chỉnh thông tin bạn đã cung cấp cho chúng tôi bằng cách nào?&rdquo; dưới đây. Tuy nhiên, lưu ý rằng việc từ chối hoặc hủy bỏ cho phép chúng tôi thu thập, sử dụng hoặc xử lý dữ liệu cá nhân của bạn có thể ảnh hưởng đến việc bạn sử dụng Các Dịch Vụ.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">4. THU THẬP CÁC DỮ LIỆU KHÁC</h2>
                    <p className="mb-4">4.1. Như với hầu hết các trang web và các ứng dụng di động khác, thiết bị của bạn gửi thông tin có thể gồm có dữ liệu về bạn, được một máy chủ web ghi lại khi bạn sử dụng Dịch Vụ của chúng tôi. Thông tin này thông thường bao gồm nhưng không giới hạn địa chỉ IP, hệ điều hành của máy tính/thiết bị di động, loại trình duyệt, loại thiết bị di động, các đặc điểm của thiết bị di động, mã định danh thiết bị thống nhất (UDID) hoặc mã định danh thiết bị di động (MEID) của thiết bị di động của bạn, địa chỉ tham chiếu của Trang Web (nếu có), các trang mà bạn đã truy cập đến trên trang web hoặc ứng dụng di động của chúng tôi và thời gian truy cập và đôi khi là &ldquo;cookie&rdquo; (có thể vô hiệu hóa bằng cách sử dụng tùy chọn trình duyệt của bạn) để giúp trang web ghi nhớ lần truy cập cuối cùng của bạn. Nếu bạn đăng nhập, thông tin này được liên kết với tài khoản cá nhân của bạn. Thông tin này cũng được đưa vào các số liệu thống kê ẩn danh để giúp chúng tôi hiểu được khách truy cập sử dụng Games và Nền tảng của chúng tôi như thế nào.</p>
                    <p className="mb-4">4.2. Các ứng dụng di động của chúng tôi có thể thu thập thông tin chính xác về địa chỉ của thiết bị di động của bạn sử dụng các công nghệ như GPS, Wi-Fi,…. Chúng tôi thu thập, sử dụng, công bố và/hoặc xử lý các thông tin này cho một hoặc nhiều mục đích bao gồm nhưng không giới hạn các dịch vụ được cung cấp dựa trên vị trí mà bạn yêu cầu hoặc chuyển các nội dung có liên quan đến bạn dựa trên vị trí của bạn hoặc cho phép bạn chia sẻ vị trí của bạn cho các Người sử dụng khác như là một phần của các Dịch vụ được cung cấp bởi các ứng dụng di động của chúng tôi. Đối với phần lớn các thiết bị di động, bạn có thể rút lại sự cho phép để chúng tôi được thu thập các thông tin này dựa trên vị trí của bạn thông qua các cài đặt trên thiết bị. Nếu bạn có câu hỏi nào về cách thức vô hiệu hóa các dịch vụ vị trí trên thiết bị di động của bạn, vui lòng liên hệ với các nhà cung cấp dịch vụ thiết bị di động hoặc nhà sản xuất thiết bị của bạn.</p>
                    <p className="mb-4">
                        4.3. Như khi bạn xem các trang hay nội dung trên trang web hoặc ứng dụng di động của chúng tôi, phần lớn các thông tin tương tự được gửi đến cho chúng tôi (bao gồm nhưng không giới hạn, địa chỉ IP, hệ điều hành, v.v..); nhưng, thay vì các số lượt xem trang, thiết bị của bạn gửi đến chúng tôi các thông tin về nội dung, quảng cáo được xem và/hoặc phần mềm được cài đặt bởi các Dịch vụ và Nền tảng và thời điểm.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">5. COOKIES</h2>
                    <p className="mb-4">5.1. Đôi khi chúng tôi hoặc các nhà cung cấp dịch vụ được cho phép và các đối tác quảng cáo của chúng tôi có thể sử dụng &ldquo;cookie&rdquo; hoặc các tính năng khác để cho phép chúng tôi hoặc các bên thứ ba thu thập hoặc chia sẻ thông tin liên quan đến việc bạn sử dụng các Dịch Vụ của chúng tôi. Các tính năng này sẽ giúp chúng tôi cải thiện Trang Web, Games và Các Dịch Vụ chúng tôi cung cấp, giúp chúng tôi đề xuất các dịch vụ và tính năng mới, và/hoặc cho phép chúng tôi và các đối tác quảng cáo của chúng tôi cung cấp các nội dung có liên quan hơn đến bạn, thông qua các hoạt động tiếp thị lại, phù hợp với các quy định của pháp luật. “Cookie” là mã định danh mà chúng tôi chuyển đến máy tính hoặc thiết bị di động của bạn có chứa dữ liệu ghi lại về máy tính hoặc thiết bị của bạn, cách thức và thời điểm Dịch vụ hoặc trang web được sử dụng hoặc truy cập, bởi bao nhiêu người và các hoạt động khác trong trang Web và Games. Chúng tôi có thể liên kết các thông tin Cookie với dữ liệu cá nhân. Cookies cũng có thể liên kết đến thông tin về những mặt hàng bạn đã chọn để mua, các trang bạn đã xem hoặc các trò chơi bạn đã chơi. Tùy thuộc vào các Dịch vụ liên quan, thông tin này có thể được sử dụng để theo dõi giỏ hàng của bạn để cung cấp nội dung cụ thể về sở thích của bạn, để cho phép chúng tôi hoặc các đối tác quảng cáo bên thứ ba của chúng tôi phân phát quảng cáo thông qua Dịch vụ hoặc trên các trang web trên internet và để giám sát việc sử dụng Dịch vụ.</p>
                    <p className="mb-4">
                        5.2. Bạn có thể từ chối việc sử dụng cookie hoặc cảnh báo web bằng cách chọn cài đặt thích hợp hoặc điều chỉnh tùy chọn của bạn trên trình duyệt hoặc thiết bị của bạn. Tuy nhiên, xin lưu ý rằng nếu bạn làm điều này, bạn có thể không sử dụng được toàn bộ chức năng của Trang web, Trò chơi hoặc Dịch vụ của chúng tôi.</p>
                    <p className="mb-4">5.3. Bạn cũng có thể chọn không tham gia các quảng cáo được cá nhân hóa trên một số ứng dụng di động bằng cách làm theo hướng dẫn dành cho Android và iOS.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">6. CHÚNG TÔI SỬ DỤNG THÔNG TIN BẠN CUNG CẤP CHO CHÚNG TÔI NHƯ THẾ NÀO?</h2>
                    <p className="mb-4">6.1. Chúng tôi có thể thu thập, sử dụng, tiết lộ và / hoặc xử lý dữ liệu cá nhân của bạn cho một hoặc nhiều mục đích sau:</p>
                    <ul className="mb-4 list-disc pl-5">
                        <li>Để xem xét và/hoặc xử lý đơn đăng ký/giao dịch của bạn với chúng tôi hoặc giao dịch hay thư từ của bạn với các bên thứ ba qua Các Dịch Vụ;</li>
                        <li>Để quản lý, điều hành, cung cấp và/hoặc quản lý việc bạn sử dụng và/hoặc truy cập Các Dịch Vụ và các Nền tảng của chúng tôi (bao gồm các sở thích của bạn), cũng như quan hệ và tài khoản người dùng của bạn với chúng tôi;</li>
                        <li>Để đáp ứng, xử lý, giải quyết hoặc hoàn tất một giao dịch và/hoặc đáp ứng các yêu cầu của bạn đối với các sản phẩm và dịch vụ nhất định và thông báo cho bạn về các vấn đề dịch vụ và các hoạt động tài khoản bất thường;</li>
                        <li>
                            Để thực thi các Điều Khoản Dịch Vụ của chúng tôi hoặc bất kỳ thỏa thuận giấy phép người dùng cuối nào áp dụng;</li>
                        <li>Để bảo vệ sự an toàn cá nhân và các quyền, tài sản hoặc sự an toàn của người khác;</li>
                        <li>Để phục vụ mục đích nhận dạng và/hoặc xác minh;</li>
                        <li>Để duy trì và quản lý và cải thiện bất kỳ bản cập nhật phần mềm nào và/hoặc các bản cập nhật khác để hỗ trợ Dịch Vụ, bao gồm khắc phục sự cố, báo cáo hoặc giải quyết bất kỳ vấn đề nào (ví dụ: phản hồi lỗi hoặc báo cáo sự cố) có thể được yêu cầu tùy lúc nhằm đảm bảo Games và/hoặc Các Dịch Vụ của chúng tôi hoạt động suôn sẻ;</li>
                        <li>Để giải quyết hoặc tạo điều kiện thuận lợi cho dịch vụ khách hàng, thực hiện các chỉ thị của bạn, giải quyết hoặc trả lời bất kỳ thắc mắc nào được gửi bởi (hoặc nhằm được gửi bởi) bạn hoặc thay mặt bạn;</li>
                        <li>Để liên hệ với bạn hoặc liên lạc với bạn qua điện thoại, tin nhắn văn bản và/hoặc tin nhắn fax, email và/hoặc thư hoặc cách khác nhằm mục đích quản trị và/hoặc quản lý quan hệ của bạn với chúng tôi hoặc việc bạn sử dụng Các Dịch Vụ của chúng tôi, chẳng hạn như ở việc truyền đạt thông tin hành chính cho bạn liên quan đến Các Dịch Vụ của chúng tôi. Bạn xác nhận và đồng ý rằng sự liên lạc như thế của chúng tôi có thể là theo cách gửi thư qua đường bưu điện, tài liệu hoặc thông báo cho bạn, có thể gồm có tiết lộ dữ liệu cá nhân nhất định về bạn để cung cấp các tài liệu đó cũng như trên bao bì/phong bì;</li>
                        <li>Để cho phép các người dùng khác tương tác, giao tiếp hoặc liên lạc với bạn, bao gồm để thông báo cho bạn khi một người dùng khác đã gửi cho bạn một tin nhắn riêng tư hoặc đăng nhận xét về bạn thông qua Games hoặc Nền tảng;</li>
                        <li>Để tiến hành các hoạt động nghiên cứu, phân tích và phát triển (bao gồm nhưng không giới hạn phân tích dữ liệu, khảo sát, phát triển và/hoặc lập đặc tính sản phẩm và dịch vụ), để phân tích cách thức bạn sử dụng Các Dịch Vụ của chúng tôi, để cải thiện Các Dịch Vụ hoặc sản phẩm của chúng tôi và/hoặc để cải thiện trải nghiệm khách hàng của bạn;</li>
                        <li>Để cho phép quảng cáo, các hoạt động kiểm tra và khảo sát khác (thông qua các bản khảo sát ngoại tuyến và trực tuyến, bao gồm cả trên các nền tảng của các bên thứ ba (ví dụ Google Forms), ngoài những hoạt động khác, xác thực quy mô và thành phần của đối tượng mục tiêu của chúng tôi, và hiểu được trải nghiệm của họ với Các Dịch Vụ của Vivabyte;</li>
                        <li>Vì mục đích tiếp thị và quảng cáo với mọi hoạt động quảng cáo phù hợp với pháp luật hiện hành, và trong trường hợp này, để giới thiệu những sản phẩm và/hoặc dịch vụ tương ứng với sở thích của bạn, để gửi cho bạn qua các phương tiện và phương thức liên lạc khác nhau (bao gồm emails và tin nhắn) các thông tin và tài liệu tiếp thị và khuyến mại liên quan đến các sản phẩm và/hoặc dịch vụ (bao gồm, nhưng không giới hạn các sản phẩm và/hoặc dịch vụ của các bên thứ ba mà Vivabyte có thể hợp tác hoặc liên kết) mà Vivabyte (và/hoặc các bên liên kết hoặc công ty có liên quan của nó) có thể bán, tiếp thị hoặc quảng bá, cho dù các sản phẩm hoặc dịch vụ đó tồn tại vào lúc này hoặc được tạo ra trong tương lai. Bạn có thể hủy đăng ký nhận các thông tin tiếp thị tại bất cứ thời điểm nào bằng cách sử dụng chức năng hủy đăng ký trong các tài liệu tiếp thị điện tử. Chúng tôi có thể sử dụng các thông tin liên hệ của bạn để gửi các bản tin và/hoặc tài liệu tiếp thị từ chúng tôi hoặc từ các công ty có liên quan của chúng tôi;</li>
                        <li>Để đáp ứng các thủ tục pháp lý hoặc để tuân thủ hoặc theo quy định của pháp luật hiện hành, và các yêu cầu của cơ quan nhà nước có thẩm quyền hoặc yêu cầu của bất cứ cơ quan tài phán nào, bao gồm nhưng không giới hạn, đáp ứng các yêu cầu đáp ứng các yêu cầu công bố thông tin theo yêu cầu của bất kỳ luật ràng buộc nào đối với Vivabyte hoặc các công ty hoặc chi nhánh liên quan của Vivabyte;</li>
                        <li>Để lập số liệu thống kê và nghiên cứu đáp ứng yêu cầu báo cáo và/hoặc duy trì sổ sách nội bộ hoặc theo quy định;</li>
                        <li>Để thực hiện quy trình tìm hiểu và xác minh hoặc các hoạt động sàng lọc khác (bao gồm nhưng không giới hạn kiểm tra lý lịch) tuân thủ các nghĩa vụ theo quy định pháp luật hoặc cơ quan nhà nước có thẩm quyền hoặc các thủ tục kiểm soát rủi ro của chúng tôi, có thể được pháp luật yêu cầu hoặc có thể đã được chúng tôi áp dụng;</li>
                        <li>Để kiểm tra Các Dịch Vụ của chúng tôi hoặc hoạt động của Vivabyte;</li>
                        <li>Để ngăn chặn hoặc điều tra bất kỳ hoạt động gian lận thực tế hoặc bị nghi ngờ nào đối với Điều khoản dịch vụ của chúng tôi, gian lận, các hành vi phi pháp, thiếu sót hay hành vi sai trái nào, cho dù có liên quan đến việc bạn sử dụng Các Dịch Vụ của chúng tôi hay không hay bất kỳ vấn đề nào phát sinh từ quan hệ của bạn với chúng tôi;</li>
                        <li>Để lưu trữ, lập máy chủ, sao lưu (cho dù là vì mục đích khôi phục sau thảm họa hoặc mục đích khác) đối với dữ liệu cá nhân của bạn, cho dù bên trong hay bên ngoài khu vực tài phán của bạn;</li>
                        <li>Để xử lý và/hoặc tạo thuận tiện cho một giao dịch tài sản kinh doanh hoặc một giao dịch tài sản kinh doanh tiềm năng, trường hợp giao dịch đó liên quan đến Vivabyte như một bên tham gia hoặc chỉ liên quan đến một công ty hay công ty liên kết của Vivabyte như một bên tham gia hoặc liên quan đến Vivabyte và/hoặc bất kỳ một hay nhiều công ty hoặc công ty liên kết của Vivabyte như (các) bên tham gia, và có thể có các tổ chức bên thứ ba khác tham gia giao dịch như thế. &ldquo;Giao dịch tài sản kinh doanh&rdquo; là các giao dịch mua, bán, cho thuê, sáp nhập, hợp nhất hoặc bất kỳ hoạt động mua lại, thanh lý, chuyển giao hay tài trợ nào của một tổ chức hoặc một phần của một tổ chức hoặc một phần hoặc toàn bộ của bất kỳ  việc kinh doanh, hoạt động kinh doanh hay tài sản nào của một tổ chức; và/hoặc</li>
                        <li>Để xác minh tư cách của bạn và/hoặc gửi đơn đăng ký/yêu cầu của bạn khi bạn đăng ký tham gia vào các cuộc thi, sự kiện hoặc giải đấu cụ thể và để trao cho bạn phần thưởng nếu có; và</li>
                        <li>Bất kỳ mục đích nào phù hợp với quy định của pháp luật hiện hành và các mục đích  mà chúng tôi thông báo cho bạn tại thời điểm xin sự cho phép của bạn.</li>
                    </ul>
                    <p className="mb-4">(gọi chung là “Các Mục Đích”)</p>
                    <p className="mb-4">6.2. Bạn xác nhận, cho phép và đồng ý rằng chúng tôi có thể truy cập, lưu trữ và tiết lộ thông tin Tài khoản và Nội dung của bạn nếu luật pháp yêu cầu làm như vậy hoặc theo lệnh của tòa án hoặc của bất kỳ cơ quan chính phủ hoặc cơ quan quản lý nào có thẩm quyền đối với Vivabyte hoặc các chi nhánh của Vivabyte hoặc với lý do chính đáng Vivabyte tin rằng việc truy cập, lưu giữ hoặc tiết lộ đó là cần thiết và chính đáng để: (a) tuân thủ quy trình pháp lý; (b) tuân thủ yêu cầu từ bất kỳ cơ quan chính phủ hoặc cơ quan quản lý nào có thẩm quyền đối với Vivabyte hoặc các chi nhánh có liên quan của Vivabyte; (c) thực thi Điều khoản Dịch vụ của chúng tôi hoặc Chính sách Bảo mật này; (d) phản hồi bất kỳ khiếu nại nào du cho là nguy cơ hoặc đang xảy ra trên thực tế để chống lại Vivabyte hoặc các chi nhánh có liên quan hoặc khiếu nại khác rằng bất kỳ Nội dung nào vi phạm quyền của bên thứ ba; (e) đáp ứng các yêu cầu của bạn về dịch vụ khách hàng; hoặc (f) bảo vệ quyền, tài sản hoặc sự an toàn cá nhân của Vivabyte hoặc các chi nhánh có liên quan, người dùng và / hoặc công chúng.</p>
                    <p className="mb-4">
                        6.3. Vì Các Mục Đích mà chúng tôi sẽ/có thể thu thập, sử dụng, tiết lộ hoặc xử lý dữ liệu cá nhân của bạn phụ thuộc vào hoàn cảnh hiện có, mục đích đó có thể không xuất hiện bên trên. Tuy nhiên, chúng tôi sẽ thông báo cho bạn biết mục đích khác đó tại thời điểm xin sự cho phép của bạn, trừ phi việc xử lý dữ liệu áp dụng mà không có sự đồng ý của bạn là được phép theo các quy định của pháp luật về bảo vệ bí mật thông tin cá nhân hoặc theo quy định pháp luật.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">7. VIVABYTE BẢO VỆ VÀ LƯU TRỮ THÔNG TIN KHÁCH HÀNG BẰNG CÁCH NÀO</h2>
                    <p className="mb-4">7.1. Chúng tôi thực hiện các biện pháp bảo mật và kiểm soát vận hành khác nhau và chúng tôi luôn nỗ lực để đảm bảo sự an toàn của dữ liệu cá nhân của bạn trên các hệ thống của chúng tôi. Dữ liệu cá nhân của người dùng được lưu trữ đằng sau các mạng bảo mật và chỉ có thể được truy cập bởi một số nhân viên có quyền truy cập đặc biệt đến các hệ thống của chúng tôi. Tuy nhiên, chắc chắn không thể có sự đảm bảo an ninh tuyệt đối.</p>
                    <p className="mb-4">7.2. Chúng tôi sẽ duy trì dữ liệu cá nhân tuân theo các quy định của pháp luật về bảo vệ bí mật thông tin cá nhân và/hoặc các điều luật hiện hành khác. Có nghĩa là, chúng tôi sẽ hủy hoặc xóa thông tin nhận dạng ra khỏi dữ liệu cá nhân của bạn khi chúng tôi có lý do hợp lý để xác định rằng (i) việc lưu giữ dữ liệu cá nhân đó không còn phục vụ mục đích thu thập dữ liệu cá nhân đó nữa; (ii) việc lưu giữ không còn cần thiết cho bất kỳ mục đích hợp pháp hay mục đích kinh doanh nào và (iii) không còn các lợi ích hợp pháp nào khác để tiếp tục lưu giữ các dữ liệu cá nhân này. Nếu bạn ngưng sử dụng Nền tảng/ Games của chúng tôi, hoặc quyền của bạn được sử dụng Nền tảng và/hoặc Các Dịch Vụ bị chấm dứt hoặc hủy bỏ, chúng tôi có thể tiếp tục lưu, sử dụng và/hoặc tiết lộ dữ liệu cá nhân của bạn tuân theo Chính sách bảo mật này và các nghĩa vụ của chúng tôi theo các quy định của pháp luật về bảo vệ bí mật thông tin cá nhân. Tùy thuộc vào quy định của pháp luật, chúng tôi có thể tiêu hủy dữ liệu cá nhân của bạn một cách an toàn mà không cần thông báo trước cho bạn.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">8. VIVABYTE CÓ TIẾT LỘ THÔNG TIN THU THẬP TỪ NGƯỜI TRUY CẬP HAY KHÔNG?</h2>
                    <p className="mb-4">8.1. Trong quá trình thực hiện hoạt động kinh doanh, chúng tôi sẽ/có thể cần phải sử dụng, xử lý, tiết lộ và/hoặc chuyển giao dữ liệu cá nhân của bạn cho các nhà cung cấp dịch vụ bên thứ ba, đại lý và/hoặc các công ty liên kết hoặc công ty liên quan của chúng tôi, và/hoặc các bên thứ ba khác có thể ở Việt Nam hoặc bên ngoài Việt Nam, vì một hay nhiều Mục Đích nói trên. Các nhà cung cấp dịch vụ bên thứ ba, đại lý và/hoặc các công ty liên kết hoặc công ty liên quan và/hoặc các bên thứ ba khác như thế sẽ xử lý dữ liệu cá nhân của bạn hoặc thay mặt chúng tôi hoặc khác, vì một hoặc nhiều Mục Đích nói trên. Các bên thứ ba như thế bao gồm:</p>
                    <ul className="mb-4 list-disc pl-5">
                        <li>Công ty con, công ty liên kết và công ty liên quan của chúng tôi;</li>
                        <li>Người sử dụng Dịch Vụ khác của chúng tôi liên quan đến việc bạn sử dụng Dịch vụ và cho một hoặc nhiều Mục đích đã nêu ở trên;</li>
                        <li>Nhà thầu, đại lý, nhà cung cấp dịch vụ và các bên thứ ba khác mà chúng tôi thuê để hỗ trợ hoặc bổ sung cho hoạt động kinh doanh của chúng tôi. Những bên này bao gồm, nhưng không giới hạn ở những bên cung cấp các dịch vụ quản trị hoặc các dịch vụ khác cho chúng tôi chẳng hạn như công ty bưu chính, đối tác phát triển games của chúng tôi, nhà cung cấp dịch vụ thanh toán và tài chính, đối tác quảng cáo và tiếp thị, công ty công nghệ thông tin, các đối tác phát triển Game, các công ty công nghệ thông tin, và trung tâm dữ liệu;</li>
                        <li>Các cơ quan chính phủ hoặc cơ quan quản lý có thẩm quyền đối với Vivabyte hoặc nếu được cho phép theo Mục 6.2;</li>
                        <li>Người mua hoặc người thừa nhiệm khác trong trường hợp sáp nhập, thoái vốn, tái cơ cấu, tái tổ chức, giải thể hoặc bán hay chuyển nhượng một phần hoặc tất cả tài sản của Vivabyte, cho dù là vấn đề đang diễn ra hay đang trong thủ tục phá sản, thanh lý hoặc thủ tục tương tự, hoặc chuyển đổi bất kỳ Dịch vụ nào của Chúng tôi, trong đó dữ liệu cá nhân Vivabyte lưu giữ về người dùng của chúng tôi nằm trong các tài sản được chuyển nhượng; hoặc cho một bên đối tác trong một giao dịch tài sản kinh doanh mà Vivabyte hoặc bất kỳ công ty liên kết hay công ty liên quan nào của nó có tham gia giao dịch, bao gồm bất cứ pháp nhân nào thừa kế hoặc pháp nhân mà chúng tôi sẽ chuyển giao vận hành bất cứ Dịch vụ nào của Chúng tôi; </li>
                        <li>Bên thứ ba mà chúng tôi tiết lộ thông tin vì một trong các Mục Đích và các bên thứ ba đó ngược lại họ sẽ thu thập và xử lý dữ liệu cá nhân của bạn vì một hoặc nhiều Mục Đích</li>
                    </ul>
                    <p className="mb-4">8.2. Chúng tôi có thể, bên cạnh những hoạt động khác, tiết lộ lịch sử chơi trò chơi của bạn và/hoặc tiết lộ hồ sơ cho thấy trò chơi nào đã được xem hoặc truy cập bằng địa chỉ IP nào. Chúng tôi cũng có thể chia sẻ thông tin thống kê và nhân khẩu học về người dùng của chúng tôi và việc họ sử dụng Dịch vụ với các đối tác quảng cáo và nhà cung cấp bên thứ ba về quảng cáo, tiếp thị lại và các chương trình khác theo luật hiện hành.</p>
                    <p className="mb-4">8.3. Ngoài ra, bạn có thể lựa chọn để đăng thông tin hoạt động người dùng của mình dưới dạng tập tin RSS có thể được người dùng khác đăng ký, có thể bao gồm thông tin liên quan đến việc chơi games của bạn, cài đặt trò chơi, kết nối với người dùng khác và thông tin khác về hoạt động tài khoản của bạn đã được đăng dưới dạng thông tin trên Nền tảng hoặc Trò chơi.</p>
                    <p className="mb-4">8.4. Để tránh nghi ngờ, trong trường hợp các quy định của pháp luật về bảo vệ bí mật thông tin cá nhân hoặc các điều luật hiện hành khác cho phép một tổ chức chẳng hạn như chúng tôi thu thập, sử dụng hoặc tiết lộ dữ liệu cá nhân của bạn mà không cần sự đồng ý của bạn, sự cho phép như thế của pháp luật sẽ tiếp tục áp dụng.</p>
                    <p className="mb-4">8.5. Các bên thứ ba có thể chặn hoặc truy cập trái phép dữ liệu cá nhân được gửi đến hoặc có trên trang web, các công nghệ có thể hoạt động không chính xác hoặc không hoạt động như dự kiến, hoặc có người có thể truy cập, lạm dụng hoặc sử dụng sai trái thông tin mà không phải lỗi của chúng tôi. Tuy nhiên chúng tôi sẽ triển khai các biện pháp bảo mật hợp lý để bảo vệ dữ liệu cá nhân của bạn theo quy định của các quy định của pháp luật về bảo vệ bí mật thông tin cá nhân; tuy nhiên không thể đảm bảo sự bảo mật tuyệt đối chẳng hạn như trường hợp tiết lộ trái phép phát sinh từ hoạt động tin tặc vì ý đồ xấu hoặc hành vi tấn cung tinh vi bưởi kẻ xấu mà không phải lỗi của chúng tôi.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">9. THÔNG TIN VỀ TRẺ EM</h2>
                    <p className="mb-4">9.1. Các Dịch Vụ này không dành cho trẻ em dưới 13 tuổi. Chúng tôi không cố tình thu thập hay lưu giữ bất kỳ dữ liệu cá nhân hay thông tin không nhận dạng cá nhân nào của bất kỳ ai dưới 13 tuổi, cũng như bất kỳ phần nào của Nền tảng, Games của chúng tôi hoặc Các Dịch Vụ khác cũng không dành cho họ. Bố/mẹ hoặc người giám hộ của trẻ em vui lòng không cho phép trẻ em mà mình đang giám hộ không đăng tải thông tin cá nhân cho Vivabyte và vui lòng tham khảo Điều khoản Dịch vụ của Vivabyte để biết thêm thông tin. Trong trường hợp thông tin cá nhân của của trẻ em dưới 13 tuổi do quý phụ huynh giám hộ được cung cấp cho Vivabyte, Bố/mẹ hoặc người giám hộ theo đồng ý với việc xử lý thông tin của trẻ em có liên quan, và sự đồng ý và thỏa thuận của bạn chịu sự điều chỉnh của các điều khoản của Chính Sách này thay mặt cho người được giám hộ. Trong trường hợp bạn thực sự không đồng ý với việc xử lý dữ liệu cá nhân của một đứa trẻ dưới 13 tuổi do bạn giám hộ, vui lòng liên hệ với Nhân viên bảo vệ dữ liệu của chúng tôi. Chúng tôi sẽ khóa bất kỳ tài khoản nào chỉ được sử dụng bởi đối tượng trẻ em như vậy và gỡ và/hoặc xóa bất kỳ dữ liệu cá nhân nào mà chúng tôi cho là đã được gửi bởi các trẻ em này mà không có sự chấp thuận của bố/mẹ hoặc người giám hộ hoặc trong trường hợp tương tự theo quy định của pháp luật hiện hành.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">10. THÔNG TIN THU THẬP BỞI CÁC BÊN THỨ BA</h2>
                    <p className="mb-4">10.1. Nền tảng và Games của chúng tôi sử dụng Google Analytics, một dịch vụ phân tích web được cung cấp bởi Google, Inc. (&ldquo;Google&rdquo;). Google Analytics sử dụng cookie, là các tập tin văn bản trên thiết bị của bạn, để giúp trang web phân tích cách thức người dùng sử dụng Dịch vụ của chúng tôi. Thông tin được tạo bởi cookie về việc bạn sử dụng Dịch vụ hoặc thiết bị (bao gồm địa chỉ IP của bạn) sẽ được gửi đến và lưu bởi Google trên các máy chủ tại Hoa Kỳ. Google sẽ sử dụng thông tin này để đánh giá việc bạn sử dụng Dịch vụ của chúng tôi, tổng hợp báo cáo về hoạt động trang web dành cho các nhà điều hành trang web và cung cấp các dịch vụ khác liên quan đến hoạt động trang web và việc sử dụng Internet. Google cũng có thể gửi thông tin này cho các bên thứ ba theo quy định của pháp luật, hoặc trường hợp các bên thứ ba xử lý thông tin thay mặt Google. Google sẽ không liên kết địa chỉ IP của bạn với bất kỳ dữ liệu nào khác mà Google nắm giữ</p>
                    <p className="mb-4">
                        10.2. Chúng tôi, và các bên thứ ba, có thể trong từng thời điểm cung cấp các bản tải về ứng dụng phần mềm cho bạn sử dụng trên hoặc thông qua Dịch vụ. Những ứng dụng này có thể truy cập riêng, và cho phép một bên thứ ba xem, thông tin nhận dạng của bạn, chẳng hạn như tên, ID người dùng của bạn, Địa chỉ IP của thiết bị của bạn hoặc thông tin khác chẳng hạn như game bạn đang chơi trong bất kỳ phiên truy cập cụ thể nào, và bất kỳ cookie nào trước đây bạn có thể đã cài đặt hoặc đã được cài đặt cho bạn bởi một ứng dụng phần mềm hoặc trang web của bên thứ ba. Ngoài ra, các ứng dụng này có thể yêu cầu bạn cung cấp thêm thông tin trực tiếp cho các bên thứ ba. Các sản phẩm hoặc dịch vụ của bên thứ ba được cung cấp thông qua các ứng dụng này không thuộc sở hữu hay quyền kiểm soát của Vivabyte. Bạn nên đọc các điều khoản và các chính sách khác được công bố bởi các bên thứ ba đó trên trang web của họ hoặc nơi khác.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">11. LOẠI TRỪ TRÁCH NHIỆM VỀ NGHĨA VỤ BẢO MẬT VÀ CÁC TRANG WEB BÊN THỨ BA</h2>
                    <p className="mb-4">11.1. CHÚNG TÔI KHÔNG ĐẢM BẢO TÍNH BẢO MẬT ĐỐI VỚI DỮ LIỆU CÁ NHÂN VÀ/HOẶC THÔNG TIN KHÁC MÀ BẠN CUNG CẤP TRÊN CÁC TRANG WEB CỦA BÊN THỨ BA. Chúng tôi thực hiện các biện pháp bảo mật khác nhau để duy trì sự an toàn của dữ liệu cá nhân của bạn mà chúng tôi lưu giữ hoặc kiểm soát. Dữ liệu cá nhân của bạn được lưu đằng sau các mạng bảo mật và chỉ có thể được truy cập bởi một số cá nhân giới hạn có quyền truy cập đặc biệt đến các hệ thống của chúng tôi, và đã được yêu cầu bảo mật dữ liệu cá nhân đó. Khi bạn đặt hàng hoặc truy cập dữ liệu cá nhân của bạn, chúng tôi đề nghị sử dụng một máy chủ bảo mật. Tất cả dữ liệu cá nhân hoặc thông tin cá nhân bạn cung cấp sẽ được mã hóa vào các cơ sở dữ liệu của chúng tôi để chỉ được truy cập như mô tả bên trên.</p>
                    <p className="mb-4">11.2. Nhằm cung cấp cho bạn giá trị gia tăng, chúng tôi có thể chọn các trang web hoặc ứng dụng hoặc dịch vụ của bên thứ ba khác nhau để liên kết, và đóng khung bên trong Nền tảng hoặc Games. Chúng tôi cũng có thể tham gia các quan hệ cùng tiếp thị và các quan hệ khác để cung cấp dịch vụ thương mại điện tử và các dịch vụ và tính năng khác cho khách truy cập. Những trang được liên kết này có các chính sách về quyền riêng tư cũng như các biện pháp bảo mật riêng và độc lập. Ngay cả khi bên thứ ba đó có liên kết với chúng tôi, chúng tôi cũng không kiểm soát các trang web/ứng dụng/dịch vụ được liên kết này, mỗi trang đó có các phương pháp bảo vệ quyền riêng tư và thu thập dữ liệu riêng biệt, độc lập với chúng tôi. Dữ liệu thu thập bởi các đối tác cùng tiếp thị của chúng tôi hoặc các trang web/ứng dụng/dịch vụ của bên thứ ba (ngay cả khi được cung cấp trên hoặc thông qua Trang web hoặc Games của chúng tôi) có thể không được nhận bởi chúng tôi.</p>
                    <p className="mb-4">11.3. Do đó chúng tôi không chịu trách nhiệm hay trách nhiệm pháp lý đối với nội dung, các biện pháp bảo mật (hoặc sự thiếu biện pháp bảo mật) và các hoạt động của các trang web/ứng dụng/dịch vụ được liên kết này. Những trang web/ứng dụng/dịch vụ được liên kết này chỉ để tạo ra sự thuận tiện cho bạn và do đó bạn tự chịu trách nhiệm khi truy cập chúng. Tuy nhiên, chúng tôi tìm cách bảo vệ tính toàn vẹn của Nền tảng và Games của chúng tôi và các liên kết được đặt trên từng trang web đó và do đó chúng tôi hoan nghênh ý kiến phản hồi về các trang web được liên kết này (bao gồm nhưng không giới hạn nếu một đường dẫn cụ thể không hoạt động).</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">12. VIVABYTE SẼ CHUYỂN THÔNG TIN CỦA BẠN RA NƯỚC NGOÀI?</h2>
                    <p className="mb-4">12.1. Thông tin và/hoặc dữ liệu cá nhân của bạn có thể được chuyển ra nước ngoài, lưu trữ hoặc xử lý bên ngoài quốc gia của bạn. Vivabyte sẽ chỉ chuyển dữ liệu cá nhân của bạn ra nước ngoài khi phù hợp với các quy định của pháp luật về bảo vệ dữ liệu cá nhân và Chính sách này. Bằng cách chấp nhận Chính sách này, bạn đồng ý với việc chuyển qua biên giới thông tin của bạn tới bất kỳ quốc gia nào nơi đặt các chi nhánh, nhà phát triển, máy chủ và/hoặc cơ sở dữ liệu của chúng tôi. Trong hầu hết các trường hợp, dữ liệu cá nhân của bạn sẽ được xử lý tại Việt Nam, nơi đặt các trung tâm dữ liệu và các máy chủ của chúng tôi hoạt động. Vì các khu vực pháp lý khác nhau có thể có các yêu cầu bảo vệ dữ liệu khác nhau, chúng tôi thực hiện các bước để triển khai các biện pháp bảo vệ thích hợp để bảo vệ dữ liệu của bạn.</p>
                    <p className="mb-4">
                        12.2. Bạn có thể tìm thấy thêm thông tin về việc chuyển ra khỏi Liên minh Châu Âu, dữ liệu cá nhân và / hoặc thông tin liên quan đến người dùng ở Liên minh Châu Âu trong phần có tiêu đề &ldquo;Quy định bổ sung chỉ dành cho người dùng ở Liên minh Châu Âu&rdquo;.</p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">
                        13. BẠN CÓ THỂ RÚT TÊN, XÓA TÊN, YÊU CẦU TRUY CẬP HOẶC ĐIỀU CHỈNH THÔNG TIN BẠN ĐÃ CUNG CẤP CHO CHÚNG TÔI BẰNG CÁCH NÀO?</h2>
                    <p className="mb-4">
                        13.1. Rút Lại Sự Đồng Ý</p>
                    <p className="mb-4">
                        13.1.1. Bạn có thể rút lại sự đồng ý cho phép thu thập, sử dụng và/hoặc tiết lộ và/hoặc yêu cầu xóa dữ liệu cá nhân của bạn mà chúng tôi đang lưu giữ hoặc kiểm soát bằng cách gửi email cho Chuyên viên Bảo Vệ Dữ Liệu của chúng tôi tại địa chỉ email homnaydidauday@gmail.com. Chúng tôi sẽ xử lý các yêu cầu này theo Chính Sách Bảo Mật và các nghĩa vụ của chúng tôi theo các quy định của pháp luật về bảo vệ dữ liệu cá nhân.</p>
                    <p className="mb-4">
                        13.1.2. Tuy nhiên, việc bạn rút lại sự cho phép và/hoặc yêu cầu xóa dữ liệu cá nhân của bạn được xử lý hoặc kiểm soát bởi chúng tôi có thể đồng nghĩa với việc chúng tôi sẽ không thể tiếp tục cung cấp các Dịch vụ đến bạn và chúng tôi có thể cần phải chấm dứt mối quan hệ hiện tại giữa bạn và/hoặc hợp đồng mà bạn có với Chúng tôi.</p>
                    <p className="mb-4">
                        13.2. Yêu Cầu Truy Cập đến hoặc Sửa Dữ Liệu Cá Nhân</p>
                    <p className="mb-4">
                        13.2.1. Nếu bạn đã đăng ký một tài khoản với chúng tôi, cá nhân bạn có thể truy cập và/hoặc sửa dữ liệu cá nhân của bạn mà chúng tôi đang lưu giữ hoặc kiểm soát thông qua trang Thiết Lập Tài Khoản hoặc nhãn trên Nền tảng hoặc Games. Nếu bạn chưa đăng ký tài khoản với chúng tôi, cá nhân bạn có thể yêu cầu truy cập và/hoặc sửa dữ liệu cá nhân của bạn mà chúng tôi đang lưu giữ hoặc kiểm soát bằng cách gửi yêu cầu bằng văn bản cho chúng tôi. Chúng tôi sẽ cần có đủ thông tin từ bạn để xác định danh tính của bạn cũng như bản chất yêu cầu của bạn để có thể giải quyết yêu cầu của bạn. Vui lòng gửi yêu cầu bằng văn bản của bạn bằng cách gửi email cho Nhân viên Quản lý Dữ liệu của chúng tôi. Ngoài ra, nếu luật pháp yêu cầu, chúng tôi sẽ thực hiện các bước để thông báo cho bất kỳ bên thứ ba nào đã nhận hoặc sử dụng Dữ liệu cá nhân của bạn về việc chỉnh sửa đó.</p>
                    <p className="mb-4">
                        13.1.2. Tuy nhiên, việc bạn rút lại sự cho phép và/hoặc yêu cầu xóa dữ liệu cá nhân của bạn được xử lý hoặc kiểm soát bởi chúng tôi có thể đồng nghĩa với việc chúng tôi sẽ không thể tiếp tục cung cấp các Dịch vụ đến bạn và chúng tôi có thể cần phải chấm dứt mối quan hệ hiện tại giữa bạn và/hoặc hợp đồng mà bạn có với Chúng tôi.</p>
                    <p className="mb-4">
                        13.2.3. Vui lòng gửi yêu cầu của bạn bằng văn bản qua email đến Nhân viên Bảo vệ Dữ liệu của chúng tôi. Theo pháp luật hiện hành, chúng tôi bảo lưu quyền chỉ phản hồi về các dữ liệu phù hợp với yêu cầu đã được nộp cho chúng tôi phù hợp với Chính sách này. </p>
                </section>
                <section className="mb-8">
                    <h2 className="text-2xl font-bold mb-2">
                        14. THẮC MẮC, QUAN NGẠI HOẶC KHIẾU NẠI? LIÊN HỆ VỚI CHÚNG TÔI</h2>
                    <p className="mb-4">
                        14.1. Nếu bạn có bất kỳ thắc mắc, băn khoăn hoặc khiếu nại nào về các phương pháp bảo vệ quyền riêng tư của chúng tôi, vui lòng liên hệ với Nhân viên Bảo vệ Dữ liệu của chúng tôi tại địa chỉ homnaydidauday@gmail.com.</p>
                    <p className="mb-4">
                        Cập nhật lần cuối: 14/3/2023 và sẽ có hiệu lực sau bảy ngày kể từ ngày đăng tải.</p>
                </section>
            </div>

            <div className="mx-auto w-full p-12 flex justify-center shadow-xl shadow-red-200 mb-20">
            </div>
        </div >
    );
}
